// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: issue438.proto

package issue438

import (
	fmt "fmt"
	_ "github.com/coderyw/protobuf/gogoproto"
	proto "github.com/coderyw/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	apipb "google.golang.org/protobuf/types/known/apipb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	sourcecontextpb "google.golang.org/protobuf/types/known/sourcecontextpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	typepb "google.golang.org/protobuf/types/known/typepb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Types struct {
	Any                  *anypb.Any                     `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
	Api                  *apipb.Api                     `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	Met                  *apipb.Method                  `protobuf:"bytes,3,opt,name=met,proto3" json:"met,omitempty"`
	Mx                   *apipb.Mixin                   `protobuf:"bytes,4,opt,name=mx,proto3" json:"mx,omitempty"`
	Dur                  *durationpb.Duration           `protobuf:"bytes,5,opt,name=dur,proto3" json:"dur,omitempty"`
	Em                   *emptypb.Empty                 `protobuf:"bytes,6,opt,name=em,proto3" json:"em,omitempty"`
	Fm                   *fieldmaskpb.FieldMask         `protobuf:"bytes,7,opt,name=fm,proto3" json:"fm,omitempty"`
	Sc                   *sourcecontextpb.SourceContext `protobuf:"bytes,8,opt,name=sc,proto3" json:"sc,omitempty"`
	St                   *structpb.Struct               `protobuf:"bytes,9,opt,name=st,proto3" json:"st,omitempty"`
	Val                  *structpb.Value                `protobuf:"bytes,10,opt,name=val,proto3" json:"val,omitempty"`
	Nlval                structpb.NullValue             `protobuf:"varint,11,opt,name=nlval,proto3,enum=google.protobuf.NullValue" json:"nlval,omitempty"`
	Stval                *wrapperspb.StringValue        `protobuf:"bytes,12,opt,name=stval,proto3" json:"stval,omitempty"`
	Bval                 *wrapperspb.BoolValue          `protobuf:"bytes,13,opt,name=bval,proto3" json:"bval,omitempty"`
	Strval               *structpb.Struct               `protobuf:"bytes,14,opt,name=strval,proto3" json:"strval,omitempty"`
	Lstv                 *structpb.ListValue            `protobuf:"bytes,15,opt,name=lstv,proto3" json:"lstv,omitempty"`
	Ts                   *timestamppb.Timestamp         `protobuf:"bytes,16,opt,name=ts,proto3" json:"ts,omitempty"`
	T                    *typepb.Type                   `protobuf:"bytes,17,opt,name=t,proto3" json:"t,omitempty"`
	F                    *typepb.Field                  `protobuf:"bytes,18,opt,name=f,proto3" json:"f,omitempty"`
	En                   *typepb.Enum                   `protobuf:"bytes,19,opt,name=en,proto3" json:"en,omitempty"`
	Enval                *typepb.EnumValue              `protobuf:"bytes,20,opt,name=enval,proto3" json:"enval,omitempty"`
	Opt                  *typepb.Option                 `protobuf:"bytes,21,opt,name=opt,proto3" json:"opt,omitempty"`
	Dbl                  *wrapperspb.DoubleValue        `protobuf:"bytes,22,opt,name=dbl,proto3" json:"dbl,omitempty"`
	Flt                  *wrapperspb.FloatValue         `protobuf:"bytes,23,opt,name=flt,proto3" json:"flt,omitempty"`
	I64                  *wrapperspb.Int64Value         `protobuf:"bytes,24,opt,name=i64,proto3" json:"i64,omitempty"`
	U64                  *wrapperspb.UInt64Value        `protobuf:"bytes,25,opt,name=u64,proto3" json:"u64,omitempty"`
	I32                  *wrapperspb.Int32Value         `protobuf:"bytes,26,opt,name=i32,proto3" json:"i32,omitempty"`
	U32                  *wrapperspb.UInt32Value        `protobuf:"bytes,27,opt,name=u32,proto3" json:"u32,omitempty"`
	Bool                 *wrapperspb.BoolValue          `protobuf:"bytes,28,opt,name=bool,proto3" json:"bool,omitempty"`
	Str                  *wrapperspb.StringValue        `protobuf:"bytes,29,opt,name=str,proto3" json:"str,omitempty"`
	Bytes                *wrapperspb.BytesValue         `protobuf:"bytes,30,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Types) Reset()         { *m = Types{} }
func (m *Types) String() string { return proto.CompactTextString(m) }
func (*Types) ProtoMessage()    {}
func (*Types) Descriptor() ([]byte, []int) {
	return fileDescriptor_43147f0c8dedbac4, []int{0}
}
func (m *Types) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Types.Unmarshal(m, b)
}
func (m *Types) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Types.Marshal(b, m, deterministic)
}
func (m *Types) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Types.Merge(m, src)
}
func (m *Types) XXX_Size() int {
	return xxx_messageInfo_Types.Size(m)
}
func (m *Types) XXX_DiscardUnknown() {
	xxx_messageInfo_Types.DiscardUnknown(m)
}

var xxx_messageInfo_Types proto.InternalMessageInfo

func (m *Types) GetAny() *anypb.Any {
	if m != nil {
		return m.Any
	}
	return nil
}

func (m *Types) GetApi() *apipb.Api {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *Types) GetMet() *apipb.Method {
	if m != nil {
		return m.Met
	}
	return nil
}

func (m *Types) GetMx() *apipb.Mixin {
	if m != nil {
		return m.Mx
	}
	return nil
}

func (m *Types) GetDur() *durationpb.Duration {
	if m != nil {
		return m.Dur
	}
	return nil
}

func (m *Types) GetEm() *emptypb.Empty {
	if m != nil {
		return m.Em
	}
	return nil
}

func (m *Types) GetFm() *fieldmaskpb.FieldMask {
	if m != nil {
		return m.Fm
	}
	return nil
}

func (m *Types) GetSc() *sourcecontextpb.SourceContext {
	if m != nil {
		return m.Sc
	}
	return nil
}

func (m *Types) GetSt() *structpb.Struct {
	if m != nil {
		return m.St
	}
	return nil
}

func (m *Types) GetVal() *structpb.Value {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Types) GetNlval() structpb.NullValue {
	if m != nil {
		return m.Nlval
	}
	return structpb.NullValue_NULL_VALUE
}

func (m *Types) GetStval() *wrapperspb.StringValue {
	if m != nil {
		return m.Stval
	}
	return nil
}

func (m *Types) GetBval() *wrapperspb.BoolValue {
	if m != nil {
		return m.Bval
	}
	return nil
}

func (m *Types) GetStrval() *structpb.Struct {
	if m != nil {
		return m.Strval
	}
	return nil
}

func (m *Types) GetLstv() *structpb.ListValue {
	if m != nil {
		return m.Lstv
	}
	return nil
}

func (m *Types) GetTs() *timestamppb.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Types) GetT() *typepb.Type {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *Types) GetF() *typepb.Field {
	if m != nil {
		return m.F
	}
	return nil
}

func (m *Types) GetEn() *typepb.Enum {
	if m != nil {
		return m.En
	}
	return nil
}

func (m *Types) GetEnval() *typepb.EnumValue {
	if m != nil {
		return m.Enval
	}
	return nil
}

func (m *Types) GetOpt() *typepb.Option {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *Types) GetDbl() *wrapperspb.DoubleValue {
	if m != nil {
		return m.Dbl
	}
	return nil
}

func (m *Types) GetFlt() *wrapperspb.FloatValue {
	if m != nil {
		return m.Flt
	}
	return nil
}

func (m *Types) GetI64() *wrapperspb.Int64Value {
	if m != nil {
		return m.I64
	}
	return nil
}

func (m *Types) GetU64() *wrapperspb.UInt64Value {
	if m != nil {
		return m.U64
	}
	return nil
}

func (m *Types) GetI32() *wrapperspb.Int32Value {
	if m != nil {
		return m.I32
	}
	return nil
}

func (m *Types) GetU32() *wrapperspb.UInt32Value {
	if m != nil {
		return m.U32
	}
	return nil
}

func (m *Types) GetBool() *wrapperspb.BoolValue {
	if m != nil {
		return m.Bool
	}
	return nil
}

func (m *Types) GetStr() *wrapperspb.StringValue {
	if m != nil {
		return m.Str
	}
	return nil
}

func (m *Types) GetBytes() *wrapperspb.BytesValue {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Types) SetAny_(val *anypb.Any) {
	if m != nil {
		m.Any = val
	}
	return
}

func (m *Types) SetApi_(val *apipb.Api) {
	if m != nil {
		m.Api = val
	}
	return
}

func (m *Types) SetMet_(val *apipb.Method) {
	if m != nil {
		m.Met = val
	}
	return
}

func (m *Types) SetMx_(val *apipb.Mixin) {
	if m != nil {
		m.Mx = val
	}
	return
}

func (m *Types) SetDur_(val *durationpb.Duration) {
	if m != nil {
		m.Dur = val
	}
	return
}

func (m *Types) SetEm_(val *emptypb.Empty) {
	if m != nil {
		m.Em = val
	}
	return
}

func (m *Types) SetFm_(val *fieldmaskpb.FieldMask) {
	if m != nil {
		m.Fm = val
	}
	return
}

func (m *Types) SetSc_(val *sourcecontextpb.SourceContext) {
	if m != nil {
		m.Sc = val
	}
	return
}

func (m *Types) SetSt_(val *structpb.Struct) {
	if m != nil {
		m.St = val
	}
	return
}

func (m *Types) SetVal_(val *structpb.Value) {
	if m != nil {
		m.Val = val
	}
	return
}

func (m *Types) SetNlval_(val structpb.NullValue) {
	if m != nil {
		m.Nlval = val
	}

}

func (m *Types) SetStval_(val *wrapperspb.StringValue) {
	if m != nil {
		m.Stval = val
	}
	return
}

func (m *Types) SetBval_(val *wrapperspb.BoolValue) {
	if m != nil {
		m.Bval = val
	}
	return
}

func (m *Types) SetStrval_(val *structpb.Struct) {
	if m != nil {
		m.Strval = val
	}
	return
}

func (m *Types) SetLstv_(val *structpb.ListValue) {
	if m != nil {
		m.Lstv = val
	}
	return
}

func (m *Types) SetTs_(val *timestamppb.Timestamp) {
	if m != nil {
		m.Ts = val
	}
	return
}

func (m *Types) SetT_(val *typepb.Type) {
	if m != nil {
		m.T = val
	}
	return
}

func (m *Types) SetF_(val *typepb.Field) {
	if m != nil {
		m.F = val
	}
	return
}

func (m *Types) SetEn_(val *typepb.Enum) {
	if m != nil {
		m.En = val
	}
	return
}

func (m *Types) SetEnval_(val *typepb.EnumValue) {
	if m != nil {
		m.Enval = val
	}
	return
}

func (m *Types) SetOpt_(val *typepb.Option) {
	if m != nil {
		m.Opt = val
	}
	return
}

func (m *Types) SetDbl_(val *wrapperspb.DoubleValue) {
	if m != nil {
		m.Dbl = val
	}
	return
}

func (m *Types) SetFlt_(val *wrapperspb.FloatValue) {
	if m != nil {
		m.Flt = val
	}
	return
}

func (m *Types) SetI64_(val *wrapperspb.Int64Value) {
	if m != nil {
		m.I64 = val
	}
	return
}

func (m *Types) SetU64_(val *wrapperspb.UInt64Value) {
	if m != nil {
		m.U64 = val
	}
	return
}

func (m *Types) SetI32_(val *wrapperspb.Int32Value) {
	if m != nil {
		m.I32 = val
	}
	return
}

func (m *Types) SetU32_(val *wrapperspb.UInt32Value) {
	if m != nil {
		m.U32 = val
	}
	return
}

func (m *Types) SetBool_(val *wrapperspb.BoolValue) {
	if m != nil {
		m.Bool = val
	}
	return
}

func (m *Types) SetStr_(val *wrapperspb.StringValue) {
	if m != nil {
		m.Str = val
	}
	return
}

func (m *Types) SetBytes_(val *wrapperspb.BytesValue) {
	if m != nil {
		m.Bytes = val
	}
	return
}

func (m *Types) IsNil() bool {
	return m == nil

}

func init() {
	proto.RegisterType((*Types)(nil), "issue438.Types")
}

func init() { proto.RegisterFile("issue438.proto", fileDescriptor_43147f0c8dedbac4) }

var fileDescriptor_43147f0c8dedbac4 = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd3, 0xdf, 0x6e, 0xd3, 0x3c,
	0x14, 0x00, 0xf0, 0x2f, 0xc9, 0xba, 0x6f, 0x78, 0x30, 0xc0, 0xec, 0x8f, 0xd7, 0x8d, 0x32, 0xc1,
	0x18, 0x03, 0x44, 0x3a, 0xda, 0xaa, 0xe2, 0x96, 0xb1, 0x21, 0x21, 0x31, 0x90, 0xbc, 0xc1, 0xed,
	0x94, 0xb4, 0x6e, 0x67, 0xcd, 0x89, 0xad, 0xd8, 0xde, 0x9a, 0xb7, 0xe1, 0x91, 0x78, 0x04, 0x04,
	0x2f, 0x82, 0xec, 0xb8, 0x80, 0x9a, 0x79, 0xda, 0x5d, 0xab, 0xf3, 0x3b, 0xc7, 0xc7, 0xe7, 0x38,
	0x60, 0x89, 0x4a, 0xa9, 0x49, 0xaf, 0xfb, 0x26, 0x16, 0x05, 0x57, 0x1c, 0x2e, 0x4c, 0xff, 0x37,
	0xf7, 0xc6, 0x54, 0x9d, 0xe9, 0x34, 0x1e, 0xf0, 0xac, 0x3d, 0xe0, 0x43, 0x52, 0x94, 0x97, 0x6d,
	0x6b, 0x52, 0x3d, 0x6a, 0x8f, 0xf9, 0x98, 0xdb, 0x3f, 0xf6, 0x57, 0x95, 0xdb, 0x5c, 0x1f, 0x73,
	0x3e, 0x66, 0xe4, 0xaf, 0x4a, 0xf2, 0xd2, 0x1b, 0x12, 0xd4, 0x85, 0x5a, 0xb3, 0xa1, 0xa1, 0x2e,
	0x12, 0x45, 0x79, 0xee, 0xe2, 0x1b, 0xb3, 0x71, 0x92, 0x09, 0x35, 0xad, 0xbb, 0x35, 0x1b, 0x1c,
	0x51, 0xc2, 0x86, 0xa7, 0x59, 0x22, 0xcf, 0x9d, 0xd8, 0x9e, 0x15, 0x92, 0xeb, 0x62, 0x40, 0x4e,
	0x07, 0x3c, 0x57, 0x64, 0xa2, 0x9c, 0xda, 0xac, 0x29, 0x55, 0xe8, 0xc1, 0x34, 0xfa, 0x68, 0x36,
	0xaa, 0x68, 0x46, 0xa4, 0x4a, 0x32, 0xe1, 0x40, 0xb3, 0x06, 0x4a, 0x41, 0x7c, 0xf7, 0xbb, 0x2c,
	0x12, 0x21, 0x48, 0x21, 0xab, 0xf8, 0xe3, 0xef, 0x00, 0x34, 0x4e, 0x4a, 0x41, 0x24, 0xdc, 0x01,
	0x51, 0x92, 0x97, 0x28, 0xd8, 0x0a, 0x76, 0x17, 0x3b, 0xcb, 0x71, 0x95, 0x17, 0x4f, 0xf3, 0xe2,
	0xb7, 0x79, 0x89, 0x0d, 0xb0, 0x4e, 0x50, 0x14, 0xfa, 0x9c, 0xa0, 0xd8, 0x00, 0xf8, 0x1c, 0x44,
	0x19, 0x51, 0x28, 0xb2, 0x6e, 0xad, 0xe6, 0x8e, 0x88, 0x3a, 0xe3, 0x43, 0x6c, 0x0c, 0xdc, 0x01,
	0x61, 0x36, 0x41, 0x73, 0x56, 0xae, 0xd6, 0x25, 0x9d, 0xd0, 0x1c, 0x87, 0xd9, 0x04, 0xbe, 0x04,
	0xd1, 0x50, 0x17, 0xa8, 0x61, 0xe1, 0x7a, 0x0d, 0x1e, 0xb8, 0xd5, 0x61, 0xa3, 0x4c, 0x51, 0x92,
	0xa1, 0x79, 0x4f, 0xd1, 0x43, 0xb3, 0x46, 0x1c, 0x92, 0x0c, 0xbe, 0x00, 0xe1, 0x28, 0x43, 0xff,
	0x5b, 0xd7, 0xac, 0xb9, 0xf7, 0x66, 0xa3, 0x47, 0x89, 0x3c, 0xc7, 0xe1, 0x28, 0x83, 0x31, 0x08,
	0xe5, 0x00, 0x2d, 0x58, 0xdb, 0xaa, 0xd9, 0x63, 0xbb, 0xdb, 0x77, 0xd5, 0x6a, 0x71, 0x28, 0x07,
	0xf0, 0x19, 0x08, 0xa5, 0x42, 0xb7, 0x3c, 0x23, 0x38, 0xb6, 0x5b, 0xc6, 0xa1, 0x54, 0x70, 0x17,
	0x44, 0x17, 0x09, 0x43, 0xc0, 0xd3, 0xed, 0xd7, 0x84, 0x69, 0x82, 0x0d, 0x81, 0x7b, 0xa0, 0x91,
	0x33, 0x63, 0x17, 0xb7, 0x82, 0xdd, 0xa5, 0x2b, 0x3a, 0xfe, 0xa4, 0x19, 0xab, 0x7c, 0x05, 0x61,
	0x07, 0x34, 0xa4, 0x32, 0x19, 0xb7, 0x6d, 0xf5, 0xcd, 0xab, 0xfa, 0xa0, 0xf9, 0xd8, 0xe5, 0x58,
	0x0a, 0x63, 0x30, 0x97, 0x9a, 0x94, 0x3b, 0x9e, 0xb1, 0xec, 0x73, 0xee, 0x0e, 0xb1, 0x0e, 0xb6,
	0xc1, 0xbc, 0x54, 0x85, 0xc9, 0x58, 0xba, 0xfe, 0xb2, 0x8e, 0x99, 0x03, 0x98, 0x54, 0x17, 0xe8,
	0xae, 0xe7, 0x80, 0x8f, 0x54, 0x2a, 0x77, 0x80, 0x71, 0x66, 0x4b, 0x4a, 0xa2, 0x7b, 0x1e, 0x7d,
	0x32, 0xfd, 0x22, 0x70, 0xa8, 0x24, 0x7c, 0x02, 0x02, 0x85, 0xee, 0x5b, 0xba, 0x52, 0xa7, 0xa5,
	0x20, 0x38, 0x50, 0x70, 0x1b, 0x04, 0x23, 0x04, 0x3d, 0xf3, 0xb6, 0x5b, 0xc7, 0xc1, 0x08, 0x3e,
	0x05, 0x21, 0xc9, 0xd1, 0x03, 0x4f, 0xad, 0xc3, 0x5c, 0x67, 0x38, 0x24, 0xb9, 0x59, 0x0a, 0xc9,
	0xcd, 0xed, 0x97, 0x3d, 0x0d, 0x1a, 0xe9, 0x06, 0x6c, 0xa1, 0xf9, 0x3a, 0xb8, 0x50, 0x68, 0xc5,
	0x33, 0xad, 0xcf, 0xa2, 0x7a, 0xc8, 0x5c, 0x28, 0x18, 0x83, 0x68, 0x98, 0x32, 0xb4, 0xea, 0xd9,
	0xde, 0x01, 0xd7, 0x29, 0x23, 0xee, 0x85, 0x0c, 0x53, 0x06, 0x5f, 0x81, 0x68, 0xc4, 0x14, 0x5a,
	0xb3, 0x7e, 0xa3, 0x7e, 0x37, 0xc6, 0x13, 0x37, 0x5a, 0xe3, 0x0c, 0xa7, 0xfd, 0x1e, 0x42, 0x1e,
	0xfe, 0x21, 0x57, 0xfd, 0x9e, 0xe3, 0xb4, 0xdf, 0x33, 0xdd, 0xe8, 0x7e, 0x0f, 0xad, 0x7b, 0xba,
	0xf9, 0xf2, 0xaf, 0xd7, 0xfd, 0x9e, 0x2d, 0xdf, 0xed, 0xa0, 0xa6, 0xbf, 0x7c, 0xb7, 0x33, 0x2d,
	0xdf, 0xed, 0xd8, 0xf2, 0xdd, 0x0e, 0xda, 0xb8, 0xa6, 0xfc, 0x1f, 0xaf, 0xad, 0x9f, 0x4b, 0x39,
	0x67, 0x68, 0xf3, 0x06, 0x0f, 0x95, 0x73, 0xf3, 0xee, 0x22, 0xa9, 0x0a, 0xf4, 0xf0, 0x06, 0x9f,
	0x82, 0x81, 0xf0, 0x35, 0x68, 0xa4, 0xa5, 0x22, 0x12, 0xb5, 0x3c, 0x17, 0xd8, 0x37, 0x51, 0xb7,
	0x5a, 0x2b, 0xf7, 0x17, 0x7e, 0xfc, 0x6c, 0xfd, 0xf7, 0xed, 0x57, 0x2b, 0x48, 0xe7, 0xad, 0xea,
	0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x3b, 0xa0, 0x21, 0xe7, 0x06, 0x00, 0x00,
}

func (m *Types) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Any != nil {
		l = m.Any.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Api != nil {
		l = m.Api.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Met != nil {
		l = m.Met.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Mx != nil {
		l = m.Mx.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Dur != nil {
		l = m.Dur.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Em != nil {
		l = m.Em.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Fm != nil {
		l = m.Fm.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Sc != nil {
		l = m.Sc.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.St != nil {
		l = m.St.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Val != nil {
		l = m.Val.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Nlval != 0 {
		n += 1 + sovIssue438(uint64(m.Nlval))
	}
	if m.Stval != nil {
		l = m.Stval.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Bval != nil {
		l = m.Bval.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Strval != nil {
		l = m.Strval.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Lstv != nil {
		l = m.Lstv.ProtoSize()
		n += 1 + l + sovIssue438(uint64(l))
	}
	if m.Ts != nil {
		l = m.Ts.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.T != nil {
		l = m.T.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.F != nil {
		l = m.F.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.En != nil {
		l = m.En.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.Enval != nil {
		l = m.Enval.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.Opt != nil {
		l = m.Opt.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.Dbl != nil {
		l = m.Dbl.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.Flt != nil {
		l = m.Flt.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.I64 != nil {
		l = m.I64.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.U64 != nil {
		l = m.U64.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.I32 != nil {
		l = m.I32.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.U32 != nil {
		l = m.U32.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.Bool != nil {
		l = m.Bool.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.Str != nil {
		l = m.Str.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.Bytes != nil {
		l = m.Bytes.ProtoSize()
		n += 2 + l + sovIssue438(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovIssue438(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIssue438(x uint64) (n int) {
	return sovIssue438(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
