// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: timefail.proto

package timefail

import (
	fmt "fmt"
	_ "github.com/coderyw/protobuf/gogoproto"
	proto "github.com/coderyw/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TimeFail struct {
	TimeTest             *time.Time `protobuf:"bytes,1,opt,name=time_test,json=timeTest,proto3,stdtime" json:"time_test,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TimeFail) Reset()         { *m = TimeFail{} }
func (m *TimeFail) String() string { return proto.CompactTextString(m) }
func (*TimeFail) ProtoMessage()    {}
func (*TimeFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_395e61815f86626a, []int{0}
}
func (m *TimeFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeFail.Unmarshal(m, b)
}
func (m *TimeFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeFail.Marshal(b, m, deterministic)
}
func (m *TimeFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeFail.Merge(m, src)
}
func (m *TimeFail) XXX_Size() int {
	return xxx_messageInfo_TimeFail.Size(m)
}
func (m *TimeFail) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeFail.DiscardUnknown(m)
}

var xxx_messageInfo_TimeFail proto.InternalMessageInfo

func (m *TimeFail) GetTimeTest() *time.Time {
	if m != nil {
		return m.TimeTest
	}
	return nil
}

func (m *TimeFail) SetTimeTest_(val *time.Time) {
	if m != nil {
		m.TimeTest = val
	}
	return
}

func (m *TimeFail) IsNil() bool {
	return m == nil

}

func init() {
	proto.RegisterType((*TimeFail)(nil), "timefail.TimeFail")
}

func init() { proto.RegisterFile("timefail.proto", fileDescriptor_395e61815f86626a) }

var fileDescriptor_395e61815f86626a = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc9, 0xcc, 0x4d,
	0x4d, 0x4b, 0xcc, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xa5, 0x0c,
	0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x93, 0xf3, 0x53, 0x52, 0x8b,
	0x2a, 0xcb, 0xf5, 0xc1, 0x6a, 0x92, 0x4a, 0xd3, 0xf4, 0xd3, 0xf3, 0xd3, 0xf3, 0xc1, 0x1c, 0x30,
	0x0b, 0xa2, 0x57, 0x4a, 0x3e, 0x3d, 0x3f, 0x3f, 0x3d, 0x27, 0x15, 0xa1, 0x0a, 0x64, 0x56, 0x71,
	0x49, 0x62, 0x6e, 0x01, 0x44, 0x81, 0x92, 0x27, 0x17, 0x47, 0x48, 0x66, 0x6e, 0xaa, 0x5b, 0x62,
	0x66, 0x8e, 0x90, 0x2d, 0x17, 0x27, 0x48, 0x3a, 0xbe, 0x24, 0xb5, 0xb8, 0x44, 0x82, 0x51, 0x81,
	0x51, 0x83, 0xdb, 0x48, 0x4a, 0x0f, 0x62, 0x80, 0x1e, 0xcc, 0x00, 0xbd, 0x10, 0x98, 0x01, 0x4e,
	0x2c, 0x13, 0xee, 0xcb, 0x33, 0x06, 0x81, 0x5d, 0x17, 0x92, 0x5a, 0x5c, 0x92, 0xc4, 0x06, 0x56,
	0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x80, 0x93, 0x0f, 0x71, 0xc0, 0x00, 0x00, 0x00,
}
