// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: m3.proto

package test_a_2

import (
	fmt "fmt"
	proto "github.com/coderyw/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type M3 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M3) Reset()         { *m = M3{} }
func (m *M3) String() string { return proto.CompactTextString(m) }
func (*M3) ProtoMessage()    {}
func (*M3) Descriptor() ([]byte, []int) {
	return fileDescriptor_9246aaa6f8876dbf, []int{0}
}
func (m *M3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M3.Unmarshal(m, b)
}
func (m *M3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M3.Marshal(b, m, deterministic)
}
func (m *M3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M3.Merge(m, src)
}
func (m *M3) XXX_Size() int {
	return xxx_messageInfo_M3.Size(m)
}
func (m *M3) XXX_DiscardUnknown() {
	xxx_messageInfo_M3.DiscardUnknown(m)
}

var xxx_messageInfo_M3 proto.InternalMessageInfo

func (m *M3) IsNil() bool {
	return m == nil

}

func init() {
	proto.RegisterType((*M3)(nil), "test.a.M3")
}

func init() { proto.RegisterFile("m3.proto", fileDescriptor_9246aaa6f8876dbf) }

var fileDescriptor_9246aaa6f8876dbf = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x35, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x49, 0x2d, 0x2e, 0xd1, 0x4b, 0x54, 0x62, 0xe1, 0x62,
	0xf2, 0x35, 0x76, 0x72, 0x8f, 0x72, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf,
	0xd5, 0x4f, 0xce, 0x4f, 0x49, 0x2d, 0xaa, 0x2c, 0xd7, 0x07, 0xab, 0x4c, 0x2a, 0x4d, 0x83, 0x30,
	0x92, 0x75, 0xd3, 0x53, 0xf3, 0x74, 0xd3, 0xf3, 0xd3, 0xf3, 0xf5, 0x41, 0x7a, 0x53, 0x12, 0x4b,
	0x12, 0xf5, 0x33, 0x73, 0x0b, 0xf2, 0x8b, 0x4a, 0x8a, 0xc1, 0x02, 0xf1, 0x89, 0xf1, 0x46, 0x49,
	0x6c, 0x60, 0xa5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xff, 0xff, 0xf7, 0x69, 0x00,
	0x00, 0x00,
}
