// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: extension_base.proto

package extension_base

import (
	fmt "fmt"
	proto "github.com/coderyw/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BaseMessage struct {
	Height                       *int32   `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *BaseMessage) Reset()         { *m = BaseMessage{} }
func (m *BaseMessage) String() string { return proto.CompactTextString(m) }
func (*BaseMessage) ProtoMessage()    {}
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_579ebed00af844f6, []int{0}
}

var extRange_BaseMessage = []proto.ExtensionRange{
	{Start: 4, End: 9},
	{Start: 16, End: 536870911},
}

func (*BaseMessage) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_BaseMessage
}

func (m *BaseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMessage.Unmarshal(m, b)
}
func (m *BaseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMessage.Marshal(b, m, deterministic)
}
func (m *BaseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMessage.Merge(m, src)
}
func (m *BaseMessage) XXX_Size() int {
	return xxx_messageInfo_BaseMessage.Size(m)
}
func (m *BaseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMessage proto.InternalMessageInfo

func (m *BaseMessage) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BaseMessage) SetHeight_(val int32) {
	if m != nil {
		*m.Height = val
	}

}

func (m *BaseMessage) IsNil() bool {
	return m == nil

}

// Another message that may be extended, using message_set_wire_format.
type OldStyleMessage struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `protobuf_messageset:"1" json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *OldStyleMessage) Reset()         { *m = OldStyleMessage{} }
func (m *OldStyleMessage) String() string { return proto.CompactTextString(m) }
func (*OldStyleMessage) ProtoMessage()    {}
func (*OldStyleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_579ebed00af844f6, []int{1}
}

var extRange_OldStyleMessage = []proto.ExtensionRange{
	{Start: 100, End: 2147483646},
}

func (*OldStyleMessage) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_OldStyleMessage
}

func (m *OldStyleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OldStyleMessage.Unmarshal(m, b)
}
func (m *OldStyleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OldStyleMessage.Marshal(b, m, deterministic)
}
func (m *OldStyleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OldStyleMessage.Merge(m, src)
}
func (m *OldStyleMessage) XXX_Size() int {
	return xxx_messageInfo_OldStyleMessage.Size(m)
}
func (m *OldStyleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OldStyleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OldStyleMessage proto.InternalMessageInfo

func (m *OldStyleMessage) IsNil() bool {
	return m == nil

}

func init() {
	proto.RegisterType((*BaseMessage)(nil), "extension_base.BaseMessage")
	proto.RegisterType((*OldStyleMessage)(nil), "extension_base.OldStyleMessage")
}

func init() { proto.RegisterFile("extension_base.proto", fileDescriptor_579ebed00af844f6) }

var fileDescriptor_579ebed00af844f6 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xad, 0x28, 0x49,
	0xcd, 0x2b, 0xce, 0xcc, 0xcf, 0x8b, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x55, 0x32, 0xe5, 0xe2, 0x76, 0x4a, 0x2c, 0x4e, 0xf5, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe3, 0x62, 0xcb, 0x48, 0xcd, 0x4c, 0xcf, 0x28, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf2, 0xb4, 0x58, 0x38, 0x58, 0x04, 0xb8, 0xb4, 0x38, 0x38, 0x04,
	0x04, 0x1a, 0x1a, 0x1a, 0x1a, 0x98, 0x94, 0xe4, 0xb9, 0xf8, 0xfd, 0x73, 0x52, 0x82, 0x4b, 0x2a,
	0x73, 0x60, 0x5a, 0xb5, 0x38, 0x38, 0x52, 0x04, 0xfe, 0xff, 0xff, 0xff, 0x9f, 0xdd, 0x8a, 0x89,
	0x83, 0xd1, 0xc9, 0x35, 0xca, 0x39, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57,
	0x3f, 0x39, 0x3f, 0x25, 0xb5, 0xa8, 0xb2, 0x5c, 0x1f, 0xec, 0x86, 0xa4, 0xd2, 0x34, 0x08, 0x23,
	0x59, 0x37, 0x3d, 0x35, 0x4f, 0x37, 0x3d, 0x3f, 0x3d, 0x5f, 0xbf, 0x24, 0xb5, 0xb8, 0x24, 0x25,
	0xb1, 0x24, 0x51, 0x1f, 0xd5, 0x79, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0xc3, 0x76, 0xaf,
	0xc5, 0x00, 0x00, 0x00,
}
