// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gogo.proto

package gogoproto

import (
	fmt "fmt"
	proto "github.com/coderyw/protobuf/proto"
	descriptor "github.com/coderyw/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// goTypeName:Router
type Router struct {
	// 对应rcp的server name
	Server *string `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	// http路由地址
	RouterPath *string `protobuf:"bytes,1,opt,name=router_path,json=routerPath" json:"router_path,omitempty"`
	// 插件
	Plugins              []string `protobuf:"bytes,3,rep,name=plugins" json:"plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Router) Reset()         { *m = Router{} }
func (m *Router) String() string { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()    {}
func (*Router) Descriptor() ([]byte, []int) {
	return fileDescriptor_592445b5231bc2b9, []int{0}
}
func (m *Router) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Router.Unmarshal(m, b)
}
func (m *Router) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Router.Marshal(b, m, deterministic)
}
func (m *Router) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Router.Merge(m, src)
}
func (m *Router) XXX_Size() int {
	return xxx_messageInfo_Router.Size(m)
}
func (m *Router) XXX_DiscardUnknown() {
	xxx_messageInfo_Router.DiscardUnknown(m)
}

var xxx_messageInfo_Router proto.InternalMessageInfo

func (m *Router) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *Router) GetRouterPath() string {
	if m != nil && m.RouterPath != nil {
		return *m.RouterPath
	}
	return ""
}

func (m *Router) GetPlugins() []string {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func (m *Router) SetServer_(val string) {
	if m != nil {
		*m.Server = val
	}

}

func (m *Router) SetRouterPath_(val string) {
	if m != nil {
		*m.RouterPath = val
	}

}

func (m *Router) SetPlugins_(val []string) {
	if m != nil {
		m.Plugins = val
	}
	return
}

func (m *Router) IsNil() bool {
	return m == nil

}

var E_GoprotoEnumPrefix = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62001,
	Name:          "gogoproto.goproto_enum_prefix",
	Tag:           "varint,62001,opt,name=goproto_enum_prefix",
	Filename:      "gogo.proto",
}

var E_GoprotoEnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62021,
	Name:          "gogoproto.goproto_enum_stringer",
	Tag:           "varint,62021,opt,name=goproto_enum_stringer",
	Filename:      "gogo.proto",
}

var E_EnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62022,
	Name:          "gogoproto.enum_stringer",
	Tag:           "varint,62022,opt,name=enum_stringer",
	Filename:      "gogo.proto",
}

var E_EnumCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         62023,
	Name:          "gogoproto.enum_customname",
	Tag:           "bytes,62023,opt,name=enum_customname",
	Filename:      "gogo.proto",
}

var E_Enumdecl = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62024,
	Name:          "gogoproto.enumdecl",
	Tag:           "varint,62024,opt,name=enumdecl",
	Filename:      "gogo.proto",
}

var E_EnumAlias = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62025,
	Name:          "gogoproto.enum_alias",
	Tag:           "varint,62025,opt,name=enum_alias",
	Filename:      "gogo.proto",
}

var E_EnumEqual = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62026,
	Name:          "gogoproto.enum_equal",
	Tag:           "varint,62026,opt,name=enum_equal",
	Filename:      "gogo.proto",
}

var E_EnumError = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62027,
	Name:          "gogoproto.enum_error",
	Tag:           "varint,62027,opt,name=enum_error",
	Filename:      "gogo.proto",
}

var E_EnumvalueCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         66001,
	Name:          "gogoproto.enumvalue_customname",
	Tag:           "bytes,66001,opt,name=enumvalue_customname",
	Filename:      "gogo.proto",
}

var E_EnumaliasCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         66002,
	Name:          "gogoproto.enumalias_customname",
	Tag:           "bytes,66002,opt,name=enumalias_customname",
	Filename:      "gogo.proto",
}

var E_GoprotoGettersAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63001,
	Name:          "gogoproto.goproto_getters_all",
	Tag:           "varint,63001,opt,name=goproto_getters_all",
	Filename:      "gogo.proto",
}

var E_GoprotoSettersAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63010,
	Name:          "gogoproto.goproto_setters_all",
	Tag:           "varint,63010,opt,name=goproto_setters_all",
	Filename:      "gogo.proto",
}

var E_GoprotoIsNilAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63011,
	Name:          "gogoproto.goproto_is_nil_all",
	Tag:           "varint,63011,opt,name=goproto_is_nil_all",
	Filename:      "gogo.proto",
}

var E_GoprotoEnumPrefixAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63002,
	Name:          "gogoproto.goproto_enum_prefix_all",
	Tag:           "varint,63002,opt,name=goproto_enum_prefix_all",
	Filename:      "gogo.proto",
}

var E_GoprotoStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63003,
	Name:          "gogoproto.goproto_stringer_all",
	Tag:           "varint,63003,opt,name=goproto_stringer_all",
	Filename:      "gogo.proto",
}

var E_VerboseEqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63004,
	Name:          "gogoproto.verbose_equal_all",
	Tag:           "varint,63004,opt,name=verbose_equal_all",
	Filename:      "gogo.proto",
}

var E_FaceAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63005,
	Name:          "gogoproto.face_all",
	Tag:           "varint,63005,opt,name=face_all",
	Filename:      "gogo.proto",
}

var E_GostringAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63006,
	Name:          "gogoproto.gostring_all",
	Tag:           "varint,63006,opt,name=gostring_all",
	Filename:      "gogo.proto",
}

var E_PopulateAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63007,
	Name:          "gogoproto.populate_all",
	Tag:           "varint,63007,opt,name=populate_all",
	Filename:      "gogo.proto",
}

var E_StringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63008,
	Name:          "gogoproto.stringer_all",
	Tag:           "varint,63008,opt,name=stringer_all",
	Filename:      "gogo.proto",
}

var E_OnlyoneAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63009,
	Name:          "gogoproto.onlyone_all",
	Tag:           "varint,63009,opt,name=onlyone_all",
	Filename:      "gogo.proto",
}

var E_EqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63013,
	Name:          "gogoproto.equal_all",
	Tag:           "varint,63013,opt,name=equal_all",
	Filename:      "gogo.proto",
}

var E_DescriptionAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63014,
	Name:          "gogoproto.description_all",
	Tag:           "varint,63014,opt,name=description_all",
	Filename:      "gogo.proto",
}

var E_TestgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63015,
	Name:          "gogoproto.testgen_all",
	Tag:           "varint,63015,opt,name=testgen_all",
	Filename:      "gogo.proto",
}

var E_BenchgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63016,
	Name:          "gogoproto.benchgen_all",
	Tag:           "varint,63016,opt,name=benchgen_all",
	Filename:      "gogo.proto",
}

var E_MarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63017,
	Name:          "gogoproto.marshaler_all",
	Tag:           "varint,63017,opt,name=marshaler_all",
	Filename:      "gogo.proto",
}

var E_UnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63018,
	Name:          "gogoproto.unmarshaler_all",
	Tag:           "varint,63018,opt,name=unmarshaler_all",
	Filename:      "gogo.proto",
}

var E_StableMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63019,
	Name:          "gogoproto.stable_marshaler_all",
	Tag:           "varint,63019,opt,name=stable_marshaler_all",
	Filename:      "gogo.proto",
}

var E_SizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63020,
	Name:          "gogoproto.sizer_all",
	Tag:           "varint,63020,opt,name=sizer_all",
	Filename:      "gogo.proto",
}

var E_GoprotoEnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63021,
	Name:          "gogoproto.goproto_enum_stringer_all",
	Tag:           "varint,63021,opt,name=goproto_enum_stringer_all",
	Filename:      "gogo.proto",
}

var E_EnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63022,
	Name:          "gogoproto.enum_stringer_all",
	Tag:           "varint,63022,opt,name=enum_stringer_all",
	Filename:      "gogo.proto",
}

var E_UnsafeMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63023,
	Name:          "gogoproto.unsafe_marshaler_all",
	Tag:           "varint,63023,opt,name=unsafe_marshaler_all",
	Filename:      "gogo.proto",
}

var E_UnsafeUnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63024,
	Name:          "gogoproto.unsafe_unmarshaler_all",
	Tag:           "varint,63024,opt,name=unsafe_unmarshaler_all",
	Filename:      "gogo.proto",
}

var E_GoprotoExtensionsMapAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63025,
	Name:          "gogoproto.goproto_extensions_map_all",
	Tag:           "varint,63025,opt,name=goproto_extensions_map_all",
	Filename:      "gogo.proto",
}

var E_GoprotoUnrecognizedAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63026,
	Name:          "gogoproto.goproto_unrecognized_all",
	Tag:           "varint,63026,opt,name=goproto_unrecognized_all",
	Filename:      "gogo.proto",
}

var E_GogoprotoImport = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63027,
	Name:          "gogoproto.gogoproto_import",
	Tag:           "varint,63027,opt,name=gogoproto_import",
	Filename:      "gogo.proto",
}

var E_ProtosizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63028,
	Name:          "gogoproto.protosizer_all",
	Tag:           "varint,63028,opt,name=protosizer_all",
	Filename:      "gogo.proto",
}

var E_CompareAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63029,
	Name:          "gogoproto.compare_all",
	Tag:           "varint,63029,opt,name=compare_all",
	Filename:      "gogo.proto",
}

var E_TypedeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63030,
	Name:          "gogoproto.typedecl_all",
	Tag:           "varint,63030,opt,name=typedecl_all",
	Filename:      "gogo.proto",
}

var E_EnumdeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63031,
	Name:          "gogoproto.enumdecl_all",
	Tag:           "varint,63031,opt,name=enumdecl_all",
	Filename:      "gogo.proto",
}

var E_GoprotoRegistration = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63032,
	Name:          "gogoproto.goproto_registration",
	Tag:           "varint,63032,opt,name=goproto_registration",
	Filename:      "gogo.proto",
}

var E_MessagenameAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63033,
	Name:          "gogoproto.messagename_all",
	Tag:           "varint,63033,opt,name=messagename_all",
	Filename:      "gogo.proto",
}

var E_GoprotoSizecacheAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63034,
	Name:          "gogoproto.goproto_sizecache_all",
	Tag:           "varint,63034,opt,name=goproto_sizecache_all",
	Filename:      "gogo.proto",
}

var E_GoprotoUnkeyedAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63035,
	Name:          "gogoproto.goproto_unkeyed_all",
	Tag:           "varint,63035,opt,name=goproto_unkeyed_all",
	Filename:      "gogo.proto",
}

var E_JsonUnAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63036,
	Name:          "gogoproto.json_un_all",
	Tag:           "varint,63036,opt,name=json_un_all",
	Filename:      "gogo.proto",
}

var E_FormAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63037,
	Name:          "gogoproto.form_all",
	Tag:           "varint,63037,opt,name=form_all",
	Filename:      "gogo.proto",
}

var E_CompatibleGoOut = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63038,
	Name:          "gogoproto.compatible_go_out",
	Tag:           "varint,63038,opt,name=compatible_go_out",
	Filename:      "gogo.proto",
}

var E_RouterPath = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Router)(nil),
	Field:         66001,
	Name:          "gogoproto.router_path",
	Tag:           "bytes,66001,opt,name=router_path",
	Filename:      "gogo.proto",
}

var E_GoprotoGetters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64001,
	Name:          "gogoproto.goproto_getters",
	Tag:           "varint,64001,opt,name=goproto_getters",
	Filename:      "gogo.proto",
}

var E_GoprotoSetters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64010,
	Name:          "gogoproto.goproto_setters",
	Tag:           "varint,64010,opt,name=goproto_setters",
	Filename:      "gogo.proto",
}

var E_GoprotoIsNil = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64011,
	Name:          "gogoproto.goproto_is_nil",
	Tag:           "varint,64011,opt,name=goproto_is_nil",
	Filename:      "gogo.proto",
}

var E_GoprotoStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64003,
	Name:          "gogoproto.goproto_stringer",
	Tag:           "varint,64003,opt,name=goproto_stringer",
	Filename:      "gogo.proto",
}

var E_VerboseEqual = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64004,
	Name:          "gogoproto.verbose_equal",
	Tag:           "varint,64004,opt,name=verbose_equal",
	Filename:      "gogo.proto",
}

var E_Face = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64005,
	Name:          "gogoproto.face",
	Tag:           "varint,64005,opt,name=face",
	Filename:      "gogo.proto",
}

var E_Gostring = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64006,
	Name:          "gogoproto.gostring",
	Tag:           "varint,64006,opt,name=gostring",
	Filename:      "gogo.proto",
}

var E_Populate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64007,
	Name:          "gogoproto.populate",
	Tag:           "varint,64007,opt,name=populate",
	Filename:      "gogo.proto",
}

var E_Stringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         67008,
	Name:          "gogoproto.stringer",
	Tag:           "varint,67008,opt,name=stringer",
	Filename:      "gogo.proto",
}

var E_Onlyone = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64009,
	Name:          "gogoproto.onlyone",
	Tag:           "varint,64009,opt,name=onlyone",
	Filename:      "gogo.proto",
}

var E_Equal = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64013,
	Name:          "gogoproto.equal",
	Tag:           "varint,64013,opt,name=equal",
	Filename:      "gogo.proto",
}

var E_Description = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64014,
	Name:          "gogoproto.description",
	Tag:           "varint,64014,opt,name=description",
	Filename:      "gogo.proto",
}

var E_Testgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64015,
	Name:          "gogoproto.testgen",
	Tag:           "varint,64015,opt,name=testgen",
	Filename:      "gogo.proto",
}

var E_Benchgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64016,
	Name:          "gogoproto.benchgen",
	Tag:           "varint,64016,opt,name=benchgen",
	Filename:      "gogo.proto",
}

var E_Marshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64017,
	Name:          "gogoproto.marshaler",
	Tag:           "varint,64017,opt,name=marshaler",
	Filename:      "gogo.proto",
}

var E_Unmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64018,
	Name:          "gogoproto.unmarshaler",
	Tag:           "varint,64018,opt,name=unmarshaler",
	Filename:      "gogo.proto",
}

var E_StableMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64019,
	Name:          "gogoproto.stable_marshaler",
	Tag:           "varint,64019,opt,name=stable_marshaler",
	Filename:      "gogo.proto",
}

var E_Sizer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64020,
	Name:          "gogoproto.sizer",
	Tag:           "varint,64020,opt,name=sizer",
	Filename:      "gogo.proto",
}

var E_UnsafeMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64023,
	Name:          "gogoproto.unsafe_marshaler",
	Tag:           "varint,64023,opt,name=unsafe_marshaler",
	Filename:      "gogo.proto",
}

var E_UnsafeUnmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64024,
	Name:          "gogoproto.unsafe_unmarshaler",
	Tag:           "varint,64024,opt,name=unsafe_unmarshaler",
	Filename:      "gogo.proto",
}

var E_GoprotoExtensionsMap = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64025,
	Name:          "gogoproto.goproto_extensions_map",
	Tag:           "varint,64025,opt,name=goproto_extensions_map",
	Filename:      "gogo.proto",
}

var E_GoprotoUnrecognized = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64026,
	Name:          "gogoproto.goproto_unrecognized",
	Tag:           "varint,64026,opt,name=goproto_unrecognized",
	Filename:      "gogo.proto",
}

var E_Protosizer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64028,
	Name:          "gogoproto.protosizer",
	Tag:           "varint,64028,opt,name=protosizer",
	Filename:      "gogo.proto",
}

var E_Compare = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64029,
	Name:          "gogoproto.compare",
	Tag:           "varint,64029,opt,name=compare",
	Filename:      "gogo.proto",
}

var E_Typedecl = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64030,
	Name:          "gogoproto.typedecl",
	Tag:           "varint,64030,opt,name=typedecl",
	Filename:      "gogo.proto",
}

var E_Messagename = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64033,
	Name:          "gogoproto.messagename",
	Tag:           "varint,64033,opt,name=messagename",
	Filename:      "gogo.proto",
}

var E_GoprotoSizecache = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64034,
	Name:          "gogoproto.goproto_sizecache",
	Tag:           "varint,64034,opt,name=goproto_sizecache",
	Filename:      "gogo.proto",
}

var E_GoprotoUnkeyed = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64035,
	Name:          "gogoproto.goproto_unkeyed",
	Tag:           "varint,64035,opt,name=goproto_unkeyed",
	Filename:      "gogo.proto",
}

var E_KeyReflect = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         64036,
	Name:          "gogoproto.key_reflect",
	Tag:           "bytes,64036,opt,name=key_reflect",
	Filename:      "gogo.proto",
}

var E_Nullable = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65001,
	Name:          "gogoproto.nullable",
	Tag:           "varint,65001,opt,name=nullable",
	Filename:      "gogo.proto",
}

var E_Embed = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65002,
	Name:          "gogoproto.embed",
	Tag:           "varint,65002,opt,name=embed",
	Filename:      "gogo.proto",
}

var E_Customtype = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65003,
	Name:          "gogoproto.customtype",
	Tag:           "bytes,65003,opt,name=customtype",
	Filename:      "gogo.proto",
}

var E_Customname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65004,
	Name:          "gogoproto.customname",
	Tag:           "bytes,65004,opt,name=customname",
	Filename:      "gogo.proto",
}

var E_Jsontag = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65005,
	Name:          "gogoproto.jsontag",
	Tag:           "bytes,65005,opt,name=jsontag",
	Filename:      "gogo.proto",
}

var E_Moretags = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65006,
	Name:          "gogoproto.moretags",
	Tag:           "bytes,65006,opt,name=moretags",
	Filename:      "gogo.proto",
}

var E_Casttype = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65007,
	Name:          "gogoproto.casttype",
	Tag:           "bytes,65007,opt,name=casttype",
	Filename:      "gogo.proto",
}

var E_Castkey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65008,
	Name:          "gogoproto.castkey",
	Tag:           "bytes,65008,opt,name=castkey",
	Filename:      "gogo.proto",
}

var E_Castvalue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65009,
	Name:          "gogoproto.castvalue",
	Tag:           "bytes,65009,opt,name=castvalue",
	Filename:      "gogo.proto",
}

var E_Stdtime = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65010,
	Name:          "gogoproto.stdtime",
	Tag:           "varint,65010,opt,name=stdtime",
	Filename:      "gogo.proto",
}

var E_Stdduration = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65011,
	Name:          "gogoproto.stdduration",
	Tag:           "varint,65011,opt,name=stdduration",
	Filename:      "gogo.proto",
}

var E_Wktpointer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65012,
	Name:          "gogoproto.wktpointer",
	Tag:           "varint,65012,opt,name=wktpointer",
	Filename:      "gogo.proto",
}

func init() {
	proto.RegisterType((*Router)(nil), "gogoproto.Router")
	proto.RegisterExtension(E_GoprotoEnumPrefix)
	proto.RegisterExtension(E_GoprotoEnumStringer)
	proto.RegisterExtension(E_EnumStringer)
	proto.RegisterExtension(E_EnumCustomname)
	proto.RegisterExtension(E_Enumdecl)
	proto.RegisterExtension(E_EnumAlias)
	proto.RegisterExtension(E_EnumEqual)
	proto.RegisterExtension(E_EnumError)
	proto.RegisterExtension(E_EnumvalueCustomname)
	proto.RegisterExtension(E_EnumaliasCustomname)
	proto.RegisterExtension(E_GoprotoGettersAll)
	proto.RegisterExtension(E_GoprotoSettersAll)
	proto.RegisterExtension(E_GoprotoIsNilAll)
	proto.RegisterExtension(E_GoprotoEnumPrefixAll)
	proto.RegisterExtension(E_GoprotoStringerAll)
	proto.RegisterExtension(E_VerboseEqualAll)
	proto.RegisterExtension(E_FaceAll)
	proto.RegisterExtension(E_GostringAll)
	proto.RegisterExtension(E_PopulateAll)
	proto.RegisterExtension(E_StringerAll)
	proto.RegisterExtension(E_OnlyoneAll)
	proto.RegisterExtension(E_EqualAll)
	proto.RegisterExtension(E_DescriptionAll)
	proto.RegisterExtension(E_TestgenAll)
	proto.RegisterExtension(E_BenchgenAll)
	proto.RegisterExtension(E_MarshalerAll)
	proto.RegisterExtension(E_UnmarshalerAll)
	proto.RegisterExtension(E_StableMarshalerAll)
	proto.RegisterExtension(E_SizerAll)
	proto.RegisterExtension(E_GoprotoEnumStringerAll)
	proto.RegisterExtension(E_EnumStringerAll)
	proto.RegisterExtension(E_UnsafeMarshalerAll)
	proto.RegisterExtension(E_UnsafeUnmarshalerAll)
	proto.RegisterExtension(E_GoprotoExtensionsMapAll)
	proto.RegisterExtension(E_GoprotoUnrecognizedAll)
	proto.RegisterExtension(E_GogoprotoImport)
	proto.RegisterExtension(E_ProtosizerAll)
	proto.RegisterExtension(E_CompareAll)
	proto.RegisterExtension(E_TypedeclAll)
	proto.RegisterExtension(E_EnumdeclAll)
	proto.RegisterExtension(E_GoprotoRegistration)
	proto.RegisterExtension(E_MessagenameAll)
	proto.RegisterExtension(E_GoprotoSizecacheAll)
	proto.RegisterExtension(E_GoprotoUnkeyedAll)
	proto.RegisterExtension(E_JsonUnAll)
	proto.RegisterExtension(E_FormAll)
	proto.RegisterExtension(E_CompatibleGoOut)
	proto.RegisterExtension(E_RouterPath)
	proto.RegisterExtension(E_GoprotoGetters)
	proto.RegisterExtension(E_GoprotoSetters)
	proto.RegisterExtension(E_GoprotoIsNil)
	proto.RegisterExtension(E_GoprotoStringer)
	proto.RegisterExtension(E_VerboseEqual)
	proto.RegisterExtension(E_Face)
	proto.RegisterExtension(E_Gostring)
	proto.RegisterExtension(E_Populate)
	proto.RegisterExtension(E_Stringer)
	proto.RegisterExtension(E_Onlyone)
	proto.RegisterExtension(E_Equal)
	proto.RegisterExtension(E_Description)
	proto.RegisterExtension(E_Testgen)
	proto.RegisterExtension(E_Benchgen)
	proto.RegisterExtension(E_Marshaler)
	proto.RegisterExtension(E_Unmarshaler)
	proto.RegisterExtension(E_StableMarshaler)
	proto.RegisterExtension(E_Sizer)
	proto.RegisterExtension(E_UnsafeMarshaler)
	proto.RegisterExtension(E_UnsafeUnmarshaler)
	proto.RegisterExtension(E_GoprotoExtensionsMap)
	proto.RegisterExtension(E_GoprotoUnrecognized)
	proto.RegisterExtension(E_Protosizer)
	proto.RegisterExtension(E_Compare)
	proto.RegisterExtension(E_Typedecl)
	proto.RegisterExtension(E_Messagename)
	proto.RegisterExtension(E_GoprotoSizecache)
	proto.RegisterExtension(E_GoprotoUnkeyed)
	proto.RegisterExtension(E_KeyReflect)
	proto.RegisterExtension(E_Nullable)
	proto.RegisterExtension(E_Embed)
	proto.RegisterExtension(E_Customtype)
	proto.RegisterExtension(E_Customname)
	proto.RegisterExtension(E_Jsontag)
	proto.RegisterExtension(E_Moretags)
	proto.RegisterExtension(E_Casttype)
	proto.RegisterExtension(E_Castkey)
	proto.RegisterExtension(E_Castvalue)
	proto.RegisterExtension(E_Stdtime)
	proto.RegisterExtension(E_Stdduration)
	proto.RegisterExtension(E_Wktpointer)
}

func init() { proto.RegisterFile("gogo.proto", fileDescriptor_592445b5231bc2b9) }

var fileDescriptor_592445b5231bc2b9 = []byte{
	// 1610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x99, 0xc9, 0x6f, 0x1c, 0xc5,
	0x17, 0xc7, 0x95, 0x5f, 0x16, 0x7b, 0xde, 0x78, 0x89, 0x27, 0xfe, 0x19, 0x13, 0x01, 0x31, 0x48,
	0x48, 0x39, 0x39, 0x12, 0x52, 0x84, 0xd2, 0x56, 0x88, 0x1c, 0xe3, 0x58, 0x09, 0x24, 0x31, 0x93,
	0x38, 0x2c, 0x39, 0x8c, 0xda, 0x33, 0xe5, 0x76, 0xe3, 0x9e, 0xae, 0xa1, 0xbb, 0x3a, 0xc9, 0xe4,
	0x86, 0xc2, 0x22, 0x88, 0xd8, 0x91, 0x20, 0x21, 0x09, 0x24, 0x61, 0xdf, 0xc3, 0xbe, 0x8b, 0x0b,
	0xfb, 0x09, 0xfe, 0x06, 0x2e, 0x80, 0xd9, 0x7d, 0xf3, 0x05, 0x55, 0xf7, 0x7b, 0x3d, 0xd5, 0xed,
	0x91, 0xaa, 0xe6, 0x36, 0xed, 0xa9, 0xcf, 0x67, 0xaa, 0x5f, 0x6d, 0xdf, 0x6e, 0x03, 0x38, 0xdc,
	0xe1, 0xa3, 0x8d, 0x80, 0x0b, 0x5e, 0x2a, 0xc8, 0xcf, 0xf1, 0xc7, 0x8d, 0x23, 0x0e, 0xe7, 0x8e,
	0xc7, 0xb6, 0xc4, 0x57, 0xb3, 0xd1, 0xdc, 0x96, 0x1a, 0x0b, 0xab, 0x81, 0xdb, 0x10, 0x3c, 0x48,
	0x1a, 0x5f, 0x73, 0x18, 0xd6, 0x95, 0x79, 0x24, 0x58, 0x50, 0x1a, 0x82, 0x75, 0x21, 0x0b, 0x8e,
	0xb0, 0x60, 0xf8, 0x7f, 0x23, 0xab, 0x36, 0x17, 0xca, 0x78, 0x55, 0xda, 0x04, 0xc5, 0x20, 0x6e,
	0x51, 0x69, 0xd8, 0x62, 0x7e, 0x78, 0x55, 0xfc, 0x25, 0x24, 0x7f, 0x9a, 0xb6, 0xc5, 0x7c, 0x69,
	0x18, 0xba, 0x1a, 0x5e, 0xe4, 0xb8, 0x7e, 0x38, 0xbc, 0x7a, 0x64, 0xf5, 0xe6, 0x42, 0x99, 0x2e,
	0xad, 0x7d, 0xb0, 0x01, 0x7b, 0x52, 0x61, 0x7e, 0x54, 0xaf, 0x34, 0x02, 0x36, 0xe7, 0x1e, 0x2b,
	0x5d, 0x31, 0x9a, 0x74, 0x6b, 0x94, 0xba, 0x35, 0x3a, 0xe9, 0x47, 0xf5, 0xfd, 0x0d, 0xe1, 0x72,
	0x3f, 0x1c, 0xbe, 0xf4, 0xf3, 0xea, 0x91, 0x55, 0x9b, 0xbb, 0xcb, 0x03, 0x88, 0xca, 0xef, 0xa6,
	0x63, 0xd0, 0x2a, 0xc3, 0xff, 0x33, 0xbe, 0x50, 0x04, 0xae, 0xef, 0xb0, 0x40, 0x63, 0xfc, 0x0a,
	0x8d, 0x1b, 0x14, 0xe3, 0x01, 0x44, 0xad, 0x09, 0xe8, 0xed, 0xc4, 0xf5, 0x35, 0xba, 0x7a, 0x98,
	0x2a, 0x99, 0x82, 0xfe, 0x58, 0x52, 0x8d, 0x42, 0xc1, 0xeb, 0xbe, 0x5d, 0x67, 0x1a, 0xcd, 0x37,
	0xb1, 0xa6, 0x50, 0xee, 0x93, 0xd8, 0x44, 0x4a, 0x59, 0x16, 0x74, 0xcb, 0xbf, 0xd4, 0x58, 0xd5,
	0xd3, 0x18, 0xbe, 0xc5, 0x8e, 0xa4, 0xed, 0xad, 0xed, 0x00, 0x71, 0x27, 0x6c, 0xcf, 0xb5, 0x43,
	0x0d, 0xfd, 0x1d, 0xd2, 0x05, 0x49, 0x8c, 0x4b, 0x20, 0xc5, 0xd9, 0x5d, 0x91, 0xad, 0xfb, 0xf1,
	0xef, 0x55, 0x7c, 0x52, 0x02, 0x2d, 0x3c, 0x08, 0xb8, 0xae, 0x88, 0x3f, 0x64, 0x70, 0x09, 0x58,
	0x87, 0x60, 0x50, 0x5e, 0x1c, 0xb1, 0xbd, 0x88, 0xa9, 0x65, 0xbc, 0xba, 0xad, 0xe8, 0x90, 0x6c,
	0x46, 0xb6, 0x1f, 0x4f, 0xac, 0x89, 0x6b, 0xb9, 0x21, 0x15, 0x28, 0x05, 0x45, 0x6f, 0x5c, 0x93,
	0x0e, 0xbd, 0x3f, 0xa9, 0xde, 0x58, 0xa0, 0x78, 0x95, 0xa9, 0xed, 0x30, 0x21, 0x58, 0x10, 0x56,
	0x6c, 0xaf, 0x5d, 0xd9, 0x76, 0xb9, 0x5e, 0x6a, 0x3c, 0xb5, 0x98, 0x9d, 0xda, 0x53, 0x09, 0x39,
	0xee, 0x79, 0xaa, 0x2f, 0x34, 0xf6, 0x5d, 0xc8, 0xf9, 0x0e, 0xb4, 0x7c, 0x37, 0x41, 0x89, 0x7c,
	0x6e, 0x58, 0xf1, 0x5d, 0xcf, 0x40, 0x77, 0x11, 0x75, 0xfd, 0x48, 0xee, 0x0e, 0xf7, 0xb9, 0x9e,
	0x94, 0xcd, 0xc0, 0x65, 0x6d, 0xd6, 0xb1, 0x81, 0xf1, 0x34, 0x1a, 0x07, 0x57, 0xac, 0x65, 0xa9,
	0x9d, 0x86, 0xc1, 0xf4, 0x9e, 0x71, 0x25, 0x19, 0x38, 0x9f, 0x41, 0x27, 0xdd, 0x1f, 0x2d, 0x42,
	0x69, 0xdc, 0x03, 0x03, 0x47, 0x58, 0x30, 0xcb, 0x43, 0x96, 0x4c, 0x63, 0x03, 0xdd, 0x19, 0xba,
	0x69, 0x04, 0xe3, 0xd9, 0x2c, 0x5d, 0xdb, 0xa0, 0x7b, 0xce, 0xae, 0x32, 0x03, 0xc5, 0x59, 0x54,
	0x74, 0xc9, 0xf6, 0x12, 0x1d, 0x87, 0x1e, 0x87, 0x27, 0xb7, 0x64, 0x80, 0x9f, 0x43, 0xbc, 0x48,
	0x0c, 0x2a, 0x1a, 0xbc, 0x11, 0x79, 0xb6, 0x30, 0xe9, 0xc1, 0xb3, 0xa4, 0x20, 0x06, 0x15, 0x1d,
	0x94, 0xf5, 0x39, 0x52, 0x84, 0x4a, 0x3d, 0x77, 0x40, 0x91, 0xfb, 0x5e, 0x93, 0xfb, 0x26, 0x9d,
	0x38, 0x8f, 0x06, 0x40, 0x44, 0x0a, 0xc6, 0xa0, 0x60, 0x3a, 0x10, 0x2f, 0x2c, 0xd2, 0x86, 0x46,
	0x23, 0x30, 0x05, 0xfd, 0x74, 0x5e, 0xb9, 0xdc, 0x37, 0x50, 0xbc, 0x88, 0x8a, 0x3e, 0x05, 0xc3,
	0xdb, 0x10, 0x2c, 0x14, 0x0e, 0x33, 0x91, 0xbc, 0x44, 0xb7, 0x81, 0x08, 0x96, 0x72, 0x96, 0xf9,
	0xd5, 0x79, 0x33, 0xc3, 0xcb, 0x54, 0x4a, 0x62, 0xa4, 0x62, 0x02, 0x7a, 0xeb, 0x76, 0x10, 0xce,
	0xdb, 0x9e, 0xd1, 0x70, 0xbc, 0x82, 0x8e, 0x9e, 0x14, 0xc2, 0x8a, 0x44, 0x7e, 0x27, 0x9a, 0x57,
	0xa9, 0x22, 0x0a, 0x86, 0x4b, 0x2f, 0x14, 0xf6, 0xac, 0xc7, 0x2a, 0x9d, 0xd8, 0x5e, 0xa3, 0xa5,
	0x97, 0xb0, 0x7b, 0x55, 0xe3, 0x18, 0x14, 0x42, 0xf7, 0xb8, 0x91, 0xe6, 0x75, 0x1a, 0xe9, 0x18,
	0x90, 0xf0, 0xed, 0x70, 0x79, 0xdb, 0x83, 0xdd, 0x40, 0xf6, 0x06, 0xca, 0x86, 0xda, 0x1c, 0xee,
	0xb8, 0x25, 0x74, 0xaa, 0x7c, 0x93, 0xb6, 0x04, 0x96, 0x73, 0x4d, 0xc3, 0x60, 0xe4, 0x87, 0xf6,
	0x5c, 0x67, 0x55, 0x7b, 0x8b, 0xaa, 0x96, 0xb0, 0x99, 0xaa, 0x1d, 0x84, 0x21, 0x34, 0x76, 0x36,
	0xae, 0x6f, 0xd3, 0xc6, 0x9a, 0xd0, 0x33, 0xd9, 0xd1, 0x3d, 0x0c, 0x1b, 0xd3, 0x72, 0x1e, 0x13,
	0xcc, 0x0f, 0x25, 0x53, 0xa9, 0xdb, 0x0d, 0x03, 0xf3, 0x25, 0x34, 0xd3, 0x8e, 0x3f, 0x99, 0x0a,
	0xf6, 0xda, 0x0d, 0x29, 0xbf, 0x0d, 0x86, 0x49, 0x1e, 0xf9, 0x01, 0xab, 0x72, 0xc7, 0x77, 0x8f,
	0xb3, 0x9a, 0x81, 0xfa, 0x9d, 0xdc, 0x50, 0xcd, 0x28, 0xb8, 0x34, 0xef, 0x86, 0xf5, 0x69, 0x74,
	0xad, 0xb8, 0xf5, 0x06, 0x0f, 0x84, 0xc6, 0xf8, 0x6e, 0xeb, 0xc4, 0xa2, 0x33, 0x2b, 0xc6, 0xac,
	0x49, 0xe8, 0x8b, 0x2f, 0x4d, 0xa7, 0xe4, 0x7b, 0x28, 0xea, 0x6d, 0x51, 0xb8, 0x71, 0x54, 0x79,
	0xbd, 0x61, 0x07, 0x26, 0xfb, 0xdf, 0xfb, 0xb4, 0x71, 0x20, 0x82, 0x1b, 0x87, 0x68, 0x36, 0x98,
	0xcc, 0x67, 0x06, 0x86, 0x0f, 0x68, 0xe3, 0x20, 0x06, 0x15, 0x14, 0xf1, 0x0c, 0x14, 0x1f, 0x92,
	0x82, 0x18, 0xa9, 0xb8, 0xa5, 0x75, 0xd0, 0x06, 0xcc, 0x71, 0x43, 0x11, 0xd8, 0xb2, 0xb5, 0x46,
	0xf5, 0xd1, 0x62, 0x36, 0x36, 0x97, 0x15, 0x54, 0xee, 0x44, 0x75, 0x16, 0x86, 0xb6, 0xc3, 0x64,
	0x1c, 0x32, 0xe8, 0xd8, 0xc7, 0xb4, 0x13, 0x29, 0x98, 0xec, 0x9b, 0x92, 0xe9, 0x65, 0xd9, 0xab,
	0x76, 0x75, 0xde, 0x44, 0xf7, 0x49, 0xae, 0x73, 0x07, 0x88, 0xcd, 0x85, 0xa9, 0xc8, 0x5f, 0x60,
	0x4d, 0xa3, 0xd9, 0xf9, 0x69, 0x2e, 0x4c, 0xcd, 0x24, 0xa4, 0xf4, 0xdd, 0x00, 0xc5, 0x3b, 0x43,
	0xee, 0x57, 0x22, 0x93, 0xdd, 0xff, 0x33, 0xf4, 0x14, 0x24, 0x32, 0xe3, 0x53, 0x94, 0xe0, 0x41,
	0xdd, 0x00, 0xfe, 0x3c, 0x8d, 0x12, 0x3c, 0xa8, 0xe3, 0xf6, 0x15, 0x4f, 0x27, 0xe1, 0xca, 0xcd,
	0xda, 0xe1, 0x15, 0x1e, 0xe9, 0x16, 0xc5, 0x17, 0xb4, 0x28, 0x5a, 0xe0, 0x14, 0xdf, 0x1f, 0x09,
	0xeb, 0x60, 0xe6, 0x49, 0xae, 0x74, 0xd5, 0x0a, 0xcb, 0x5e, 0x26, 0xe6, 0x79, 0x2d, 0x9b, 0xab,
	0x8b, 0xd7, 0x0d, 0x8c, 0xa6, 0xab, 0x6b, 0x34, 0x79, 0x56, 0x54, 0x1f, 0xff, 0xac, 0x3d, 0xd0,
	0x9f, 0x4b, 0xc2, 0xa5, 0x4d, 0x6d, 0xcc, 0xf1, 0xa0, 0x93, 0xfa, 0xee, 0x25, 0x9c, 0x0c, 0xd9,
	0x20, 0xac, 0xba, 0x42, 0x53, 0xd7, 0x83, 0x39, 0x17, 0x86, 0x60, 0x6b, 0x0a, 0xfa, 0xb2, 0x09,
	0x58, 0xaf, 0x3a, 0x89, 0xaa, 0x1e, 0x35, 0x00, 0x5b, 0x37, 0xcb, 0x6d, 0x29, 0x1b, 0x53, 0xf5,
	0xaa, 0x13, 0x4b, 0xd9, 0x2c, 0x9d, 0x3e, 0x2a, 0xee, 0x82, 0xde, 0x4c, 0x44, 0xd5, 0xab, 0xee,
	0xa1, 0x5e, 0xa9, 0x09, 0xd5, 0xda, 0x0a, 0x6b, 0x64, 0xdc, 0xd4, 0xe3, 0xf7, 0x22, 0x1e, 0x37,
	0xb7, 0xb6, 0x43, 0x37, 0xc5, 0x4c, 0x3d, 0x7a, 0x1f, 0xa2, 0x29, 0x22, 0x71, 0x8a, 0x98, 0x7a,
	0xfc, 0x7e, 0xc2, 0x09, 0x91, 0xb8, 0x79, 0x09, 0xbf, 0x3c, 0xb9, 0x06, 0x63, 0x02, 0xd5, 0x6e,
	0x0c, 0xba, 0x30, 0x5b, 0xea, 0xe9, 0x07, 0xf0, 0xc7, 0x89, 0xb0, 0xae, 0x87, 0xb5, 0x86, 0x05,
	0x7f, 0x08, 0xd1, 0xa4, 0xbd, 0x35, 0x01, 0x45, 0x25, 0x4f, 0xea, 0xf1, 0x87, 0x11, 0x57, 0x29,
	0xd9, 0x75, 0xcc, 0x93, 0x7a, 0xc1, 0x23, 0xd4, 0x75, 0x24, 0x64, 0xd9, 0x28, 0x4a, 0xea, 0xe9,
	0x47, 0xa9, 0xea, 0x84, 0x58, 0x3b, 0xa0, 0x90, 0xc6, 0x03, 0x3d, 0xff, 0x18, 0xf2, 0x2d, 0x46,
	0x56, 0x40, 0x89, 0x27, 0x7a, 0xc5, 0xe3, 0x54, 0x01, 0x85, 0x92, 0xcb, 0x28, 0x1f, 0x39, 0xf5,
	0xa6, 0x27, 0x68, 0x19, 0xe5, 0x12, 0xa7, 0x1c, 0xcd, 0xf8, 0x94, 0xd6, 0x2b, 0x9e, 0xa4, 0xd1,
	0x8c, 0xdb, 0xcb, 0x6e, 0xe4, 0x33, 0x9c, 0xde, 0xf1, 0x14, 0x75, 0x23, 0x17, 0xe1, 0xac, 0x69,
	0x28, 0xad, 0xcc, 0x6f, 0x7a, 0xdf, 0xd3, 0xe8, 0x1b, 0x58, 0x11, 0xdf, 0xac, 0x5b, 0x61, 0xa8,
	0x7d, 0x76, 0xd3, 0x5b, 0x4f, 0x2d, 0xe5, 0x9e, 0xb6, 0xd5, 0xe8, 0x66, 0x1d, 0x6c, 0x85, 0x00,
	0x35, 0xb7, 0xe9, 0xb5, 0xa7, 0x97, 0xb2, 0x47, 0xad, 0x1a, 0xdb, 0xac, 0x71, 0x80, 0x56, 0x64,
	0xd2, 0xbb, 0xce, 0xa0, 0x4b, 0x81, 0xe4, 0xd2, 0xc0, 0xc4, 0xa4, 0xe7, 0xcf, 0xd2, 0xd2, 0x40,
	0x42, 0x2e, 0x0d, 0x0a, 0x4b, 0x7a, 0xfa, 0x1c, 0x2d, 0x0d, 0x42, 0xe4, 0xcc, 0x56, 0xf2, 0x88,
	0xde, 0x70, 0x9e, 0x66, 0xb6, 0x42, 0x59, 0xfb, 0x60, 0x60, 0x45, 0x84, 0xd1, 0xab, 0x2e, 0xa0,
	0x6a, 0x7d, 0x3e, 0xc1, 0xa8, 0xa7, 0x20, 0xc6, 0x17, 0xbd, 0xed, 0x62, 0xee, 0x14, 0xc4, 0xf4,
	0x62, 0xed, 0x84, 0xe2, 0x02, 0x6b, 0x56, 0x02, 0x36, 0xe7, 0xb1, 0xaa, 0xd0, 0x7b, 0x9e, 0x5f,
	0x4a, 0x5e, 0x4c, 0xc2, 0x02, 0x6b, 0x96, 0x13, 0xc8, 0x1a, 0x83, 0x6e, 0x3f, 0xf2, 0x3c, 0xb9,
	0x00, 0x4b, 0x57, 0xb6, 0x89, 0x1e, 0xcc, 0x4b, 0x33, 0xc3, 0x2f, 0xcb, 0x58, 0x61, 0x02, 0xac,
	0xad, 0xb0, 0x96, 0xd5, 0x67, 0x59, 0x4d, 0x47, 0xfe, 0xba, 0x4c, 0x9b, 0xae, 0x6c, 0x6d, 0xed,
	0x00, 0x48, 0xde, 0xd6, 0xc9, 0xa1, 0xd2, 0xb1, 0xbf, 0x2d, 0x63, 0xa7, 0x5b, 0x48, 0x4b, 0x10,
	0x0f, 0xac, 0x46, 0xb0, 0x98, 0x15, 0xc4, 0xa3, 0xba, 0x0d, 0xba, 0x64, 0x82, 0x13, 0xb6, 0xa3,
	0xa3, 0x7f, 0x47, 0x9a, 0xda, 0xcb, 0x82, 0xd5, 0x79, 0xc0, 0x84, 0xed, 0x84, 0x3a, 0xf6, 0x0f,
	0x64, 0x53, 0x40, 0xc2, 0x55, 0x3b, 0x14, 0x26, 0xf7, 0xfd, 0x27, 0xc1, 0x04, 0xc8, 0x4e, 0xcb,
	0xcf, 0x0b, 0xac, 0xa9, 0x63, 0xff, 0xa2, 0x4e, 0x63, 0x7b, 0x6b, 0x3b, 0x14, 0xe4, 0xc7, 0xf8,
	0x05, 0xaa, 0x0e, 0xfe, 0x1b, 0xe1, 0x16, 0x21, 0x7f, 0x39, 0x14, 0x35, 0xe1, 0xea, 0x8b, 0xfd,
	0x0f, 0x8e, 0x34, 0xb5, 0xb7, 0xc6, 0xa1, 0x18, 0x8a, 0x5a, 0x2d, 0xc2, 0xa7, 0x12, 0x0d, 0xfe,
	0xef, 0x72, 0xfa, 0xa2, 0x2a, 0x65, 0xe4, 0x68, 0x1f, 0x5d, 0x10, 0x0d, 0xee, 0xfa, 0x82, 0x05,
	0x3a, 0xc3, 0x12, 0x1a, 0x14, 0x64, 0xe7, 0x8d, 0x72, 0xcd, 0x65, 0x98, 0x9d, 0x30, 0xc5, 0xa7,
	0xf8, 0x74, 0xbc, 0x4f, 0xdd, 0x71, 0xad, 0xe3, 0x8a, 0xf9, 0x68, 0x76, 0xb4, 0xca, 0xeb, 0x5b,
	0xaa, 0xbc, 0xc6, 0x82, 0xe6, 0xd1, 0xd6, 0x3f, 0x55, 0xd2, 0x78, 0xfc, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0x6b, 0xe8, 0x25, 0x87, 0x19, 0x00, 0x00,
}
