// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: issue322.proto

package test

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/coderyw/protobuf/gogoproto"
	proto "github.com/coderyw/protobuf/proto"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OneofTest struct {
	// Types that are valid to be assigned to Union:
	//
	//	*OneofTest_I
	Union                isOneofTest_Union `protobuf_oneof:"union"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OneofTest) Reset()         { *m = OneofTest{} }
func (m *OneofTest) String() string { return proto.CompactTextString(m) }
func (*OneofTest) ProtoMessage()    {}
func (*OneofTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbf4e8d164dccde1, []int{0}
}
func (m *OneofTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofTest.Unmarshal(m, b)
}
func (m *OneofTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofTest.Marshal(b, m, deterministic)
}
func (m *OneofTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofTest.Merge(m, src)
}
func (m *OneofTest) XXX_Size() int {
	return xxx_messageInfo_OneofTest.Size(m)
}
func (m *OneofTest) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofTest.DiscardUnknown(m)
}

var xxx_messageInfo_OneofTest proto.InternalMessageInfo

const Default_OneofTest_I int32 = 4

type isOneofTest_Union interface {
	isOneofTest_Union()
	Equal(interface{}) bool
	Compare(interface{}) int
}

type OneofTest_I struct {
	I int32 `protobuf:"varint,1,opt,name=i,oneof,def=4" json:"i,omitempty"`
}

func (*OneofTest_I) isOneofTest_Union() {}

func (m *OneofTest) GetUnion() isOneofTest_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *OneofTest) GetI() int32 {
	if x, ok := m.GetUnion().(*OneofTest_I); ok {
		return x.I
	}
	return Default_OneofTest_I
}

func (m *OneofTest) IsNil() bool {
	return m == nil

}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneofTest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OneofTest_I)(nil),
	}
}

func init() {
	proto.RegisterType((*OneofTest)(nil), "test.OneofTest")
}

func init() { proto.RegisterFile("issue322.proto", fileDescriptor_fbf4e8d164dccde1) }

var fileDescriptor_fbf4e8d164dccde1 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2c, 0x2e, 0x2e,
	0x4d, 0x35, 0x36, 0x32, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x49, 0x2d, 0x2e,
	0x91, 0x32, 0x48, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xce, 0x4f,
	0x49, 0x2d, 0xaa, 0x2c, 0xd7, 0x07, 0xcb, 0x27, 0x95, 0xa6, 0xe9, 0xa7, 0xe7, 0xa7, 0xe7, 0x83,
	0x39, 0x60, 0x16, 0x44, 0x9f, 0x92, 0x3a, 0x17, 0xa7, 0x7f, 0x5e, 0x6a, 0x7e, 0x5a, 0x48, 0x6a,
	0x71, 0x89, 0x90, 0x20, 0x17, 0x63, 0xa6, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xab, 0x15, 0xa3, 0x89,
	0x07, 0x43, 0x10, 0x63, 0xa6, 0x13, 0x3b, 0x17, 0x6b, 0x69, 0x5e, 0x66, 0x7e, 0x9e, 0x93, 0xc8,
	0x87, 0x87, 0x72, 0x8c, 0x3f, 0x1e, 0xca, 0x31, 0xae, 0x78, 0x24, 0xc7, 0xb8, 0xe3, 0x91, 0x1c,
	0xe3, 0x8a, 0xc7, 0x72, 0x8c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xe6, 0x95, 0x4e, 0x87,
	0x00, 0x00, 0x00,
}

func (this *OneofTest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*OneofTest)
	if !ok {
		that2, ok := that.(OneofTest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if that1.Union == nil {
		if this.Union != nil {
			return 1
		}
	} else if this.Union == nil {
		return -1
	} else {
		thisType := -1
		switch this.Union.(type) {
		case *OneofTest_I:
			thisType = 0
		default:
			panic(fmt.Sprintf("compare: unexpected type %T in oneof", this.Union))
		}
		that1Type := -1
		switch that1.Union.(type) {
		case *OneofTest_I:
			that1Type = 0
		default:
			panic(fmt.Sprintf("compare: unexpected type %T in oneof", that1.Union))
		}
		if thisType == that1Type {
			if c := this.Union.Compare(that1.Union); c != 0 {
				return c
			}
		} else if thisType < that1Type {
			return -1
		} else if thisType > that1Type {
			return 1
		}
	}
	if c := bytes.Compare(this.XXX_unrecognized, that1.XXX_unrecognized); c != 0 {
		return c
	}
	return 0
}
func (this *OneofTest_I) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*OneofTest_I)
	if !ok {
		that2, ok := that.(OneofTest_I)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.I != that1.I {
		if this.I < that1.I {
			return -1
		}
		return 1
	}
	return 0
}
func (this *OneofTest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OneofTest)
	if !ok {
		that2, ok := that.(OneofTest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.Union == nil {
		if this.Union != nil {
			return false
		}
	} else if this.Union == nil {
		return false
	} else if !this.Union.Equal(that1.Union) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *OneofTest_I) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OneofTest_I)
	if !ok {
		that2, ok := that.(OneofTest_I)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.I != that1.I {
		return false
	}
	return true
}
func (this *OneofTest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&test.OneofTest{")
	if this.Union != nil {
		s = append(s, "Union: "+fmt.Sprintf("%#v", this.Union)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OneofTest_I) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&test.OneofTest_I{` +
		`I:` + fmt.Sprintf("%#v", this.I) + `}`}, ", ")
	return s
}
func valueToGoStringIssue322(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func NewPopulatedOneofTest(r randyIssue322, easy bool) *OneofTest {
	this := &OneofTest{}
	oneofNumber_Union := []int32{1}[r.Intn(1)]
	switch oneofNumber_Union {
	case 1:
		this.Union = NewPopulatedOneofTest_I(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedIssue322(r, 2)
	}
	return this
}

func NewPopulatedOneofTest_I(r randyIssue322, easy bool) *OneofTest_I {
	this := &OneofTest_I{}
	this.I = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.I *= -1
	}
	return this
}

type randyIssue322 interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneIssue322(r randyIssue322) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringIssue322(r randyIssue322) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneIssue322(r)
	}
	return string(tmps)
}
func randUnrecognizedIssue322(r randyIssue322, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldIssue322(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldIssue322(dAtA []byte, r randyIssue322, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateIssue322(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateIssue322(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateIssue322(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateIssue322(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateIssue322(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateIssue322(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateIssue322(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
