// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package test_proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_coderyw_go_proto_validators "github.com/coderyw/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GoEnum) Validate() error {
	return nil
}
func (this *GoTestField) Validate() error {
	return nil
}
func (this *GoTest) Validate() error {
	if this.RequiredField != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.RequiredField))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("RequiredField", err)
		}
	}
	for _, item := range this.RepeatedField {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("RepeatedField", err)
		}
	}
	if this.OptionalField != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.OptionalField))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("OptionalField", err)
		}
	}
	return nil
}
func (this *GoTest_RequiredGroup) Validate() error {
	return nil
}
func (this *GoTest_RepeatedGroup) Validate() error {
	return nil
}
func (this *GoTest_OptionalGroup) Validate() error {
	return nil
}
func (this *GoTestRequiredGroupField) Validate() error {
	return nil
}
func (this *GoTestRequiredGroupField_Group) Validate() error {
	return nil
}
func (this *GoSkipTest) Validate() error {
	return nil
}
func (this *GoSkipTest_SkipGroup) Validate() error {
	return nil
}
func (this *NonPackedTest) Validate() error {
	return nil
}
func (this *PackedTest) Validate() error {
	return nil
}
func (this *MaxTag) Validate() error {
	return nil
}
func (this *OldMessage) Validate() error {
	if this.Nested != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.Nested))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Nested", err)
		}
	}
	return nil
}
func (this *OldMessage_Nested) Validate() error {
	return nil
}
func (this *NewMessage) Validate() error {
	if this.Nested != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.Nested))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Nested", err)
		}
	}
	return nil
}
func (this *NewMessage_Nested) Validate() error {
	return nil
}
func (this *InnerMessage) Validate() error {
	return nil
}
func (this *OtherMessage) Validate() error {
	if this.Inner != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.Inner))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Inner", err)
		}
	}
	return nil
}
func (this *RequiredInnerMessage) Validate() error {
	if this.LeoFinallyWonAnOscar != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.LeoFinallyWonAnOscar))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("LeoFinallyWonAnOscar", err)
		}
	}
	return nil
}
func (this *MyMessage) Validate() error {
	if this.Inner != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.Inner))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Inner", err)
		}
	}
	for _, item := range this.Others {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Others", err)
		}
	}
	if this.WeMustGoDeeper != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.WeMustGoDeeper))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("WeMustGoDeeper", err)
		}
	}
	for _, item := range this.RepInner {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("RepInner", err)
		}
	}
	return nil
}
func (this *MyMessage_SomeGroup) Validate() error {
	return nil
}
func (this *Ext) Validate() error {
	for _, item := range this.MapField {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("MapField", err)
		}
	}
	return nil
}
func (this *ComplexExtension) Validate() error {
	return nil
}
func (this *DefaultsMessage) Validate() error {
	return nil
}
func (this *MyMessageSet) Validate() error {
	return nil
}
func (this *Empty) Validate() error {
	return nil
}
func (this *MessageList) Validate() error {
	return nil
}
func (this *MessageList_Message) Validate() error {
	return nil
}
func (this *Strings) Validate() error {
	return nil
}
func (this *Defaults) Validate() error {
	if this.Sub != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.Sub))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Sub", err)
		}
	}
	return nil
}
func (this *SubDefaults) Validate() error {
	return nil
}
func (this *RepeatedEnum) Validate() error {
	return nil
}
func (this *MoreRepeated) Validate() error {
	return nil
}
func (this *GroupOld) Validate() error {
	return nil
}
func (this *GroupOld_G) Validate() error {
	return nil
}
func (this *GroupNew) Validate() error {
	return nil
}
func (this *GroupNew_G) Validate() error {
	return nil
}
func (this *FloatingPoint) Validate() error {
	return nil
}
func (this *MessageWithMap) Validate() error {
	for _, item := range this.NameMapping {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("NameMapping", err)
		}
	}
	for _, item := range this.MsgMapping {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("MsgMapping", err)
		}
	}
	for _, item := range this.ByteMapping {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("ByteMapping", err)
		}
	}
	for _, item := range this.StrToStr {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("StrToStr", err)
		}
	}
	return nil
}
func (this *Oneof) Validate() error {
	if this.Union != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.Union))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Union", err)
		}
	}
	return nil
}
func (this *Oneof_F_Group) Validate() error {
	return nil
}
func (this *Communique) Validate() error {
	if this.Union != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(this.Union))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Union", err)
		}
	}
	return nil
}
func (this *TestUTF8) Validate() error {
	for _, item := range this.MapKey {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("MapKey", err)
		}
	}
	for _, item := range this.MapValue {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("MapValue", err)
		}
	}
	return nil
}
