// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test_import_all.proto

package imports

import (
	fmt "fmt"
	proto "github.com/coderyw/protobuf/proto"
	fmt1 "github.com/coderyw/protobuf/protoc-gen-gogo/testdata/imports/fmt"
	test_a_1 "github.com/coderyw/protobuf/protoc-gen-gogo/testdata/imports/test_a_1"
	test_a_2 "github.com/coderyw/protobuf/protoc-gen-gogo/testdata/imports/test_a_2"
	test_b_1 "github.com/coderyw/protobuf/protoc-gen-gogo/testdata/imports/test_b_1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type All struct {
	Am1                  *test_a_1.M1 `protobuf:"bytes,1,opt,name=am1,proto3" json:"am1,omitempty"`
	Am2                  *test_a_1.M2 `protobuf:"bytes,2,opt,name=am2,proto3" json:"am2,omitempty"`
	Am3                  *test_a_2.M3 `protobuf:"bytes,3,opt,name=am3,proto3" json:"am3,omitempty"`
	Am4                  *test_a_2.M4 `protobuf:"bytes,4,opt,name=am4,proto3" json:"am4,omitempty"`
	Bm1                  *test_b_1.M1 `protobuf:"bytes,5,opt,name=bm1,proto3" json:"bm1,omitempty"`
	Bm2                  *test_b_1.M2 `protobuf:"bytes,6,opt,name=bm2,proto3" json:"bm2,omitempty"`
	Fmt                  *fmt1.M      `protobuf:"bytes,7,opt,name=fmt,proto3" json:"fmt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *All) Reset()         { *m = All{} }
func (m *All) String() string { return proto.CompactTextString(m) }
func (*All) ProtoMessage()    {}
func (*All) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aebe744efed8f5b, []int{0}
}
func (m *All) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_All.Unmarshal(m, b)
}
func (m *All) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_All.Marshal(b, m, deterministic)
}
func (m *All) XXX_Merge(src proto.Message) {
	xxx_messageInfo_All.Merge(m, src)
}
func (m *All) XXX_Size() int {
	return xxx_messageInfo_All.Size(m)
}
func (m *All) XXX_DiscardUnknown() {
	xxx_messageInfo_All.DiscardUnknown(m)
}

var xxx_messageInfo_All proto.InternalMessageInfo

func (m *All) GetAm1() *test_a_1.M1 {
	if m != nil {
		return m.Am1
	}
	return nil
}

func (m *All) GetAm2() *test_a_1.M2 {
	if m != nil {
		return m.Am2
	}
	return nil
}

func (m *All) GetAm3() *test_a_2.M3 {
	if m != nil {
		return m.Am3
	}
	return nil
}

func (m *All) GetAm4() *test_a_2.M4 {
	if m != nil {
		return m.Am4
	}
	return nil
}

func (m *All) GetBm1() *test_b_1.M1 {
	if m != nil {
		return m.Bm1
	}
	return nil
}

func (m *All) GetBm2() *test_b_1.M2 {
	if m != nil {
		return m.Bm2
	}
	return nil
}

func (m *All) GetFmt() *fmt1.M {
	if m != nil {
		return m.Fmt
	}
	return nil
}

func (m *All) SetAm1_(val *test_a_1.M1) {
	if m != nil {
		m.Am1 = val
	}
	return
}

func (m *All) SetAm2_(val *test_a_1.M2) {
	if m != nil {
		m.Am2 = val
	}
	return
}

func (m *All) SetAm3_(val *test_a_2.M3) {
	if m != nil {
		m.Am3 = val
	}
	return
}

func (m *All) SetAm4_(val *test_a_2.M4) {
	if m != nil {
		m.Am4 = val
	}
	return
}

func (m *All) SetBm1_(val *test_b_1.M1) {
	if m != nil {
		m.Bm1 = val
	}
	return
}

func (m *All) SetBm2_(val *test_b_1.M2) {
	if m != nil {
		m.Bm2 = val
	}
	return
}

func (m *All) SetFmt_(val *fmt1.M) {
	if m != nil {
		m.Fmt = val
	}
	return
}

func (m *All) IsNil() bool {
	return m == nil

}

func init() {
	proto.RegisterType((*All)(nil), "test.All")
}

func init() { proto.RegisterFile("test_import_all.proto", fileDescriptor_4aebe744efed8f5b) }

var fileDescriptor_4aebe744efed8f5b = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd0, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x07, 0x70, 0x6a, 0x66, 0x85, 0x78, 0x91, 0x8a, 0x10, 0xc5, 0x83, 0xec, 0xe4, 0x65, 0x09,
	0x49, 0x7a, 0x14, 0x41, 0xef, 0xbb, 0xec, 0xe8, 0xa5, 0x24, 0x5d, 0x5b, 0x07, 0x7d, 0xa6, 0x74,
	0x6f, 0x88, 0x9f, 0xd6, 0xaf, 0x22, 0xc9, 0x53, 0x90, 0x6e, 0xbd, 0x85, 0xff, 0xef, 0x1f, 0x5e,
	0xf2, 0xf8, 0x0d, 0x36, 0x7b, 0xac, 0x76, 0x30, 0x84, 0x11, 0x2b, 0xd7, 0xf7, 0x72, 0x18, 0x03,
	0x86, 0x62, 0x11, 0xe3, 0xbb, 0x5b, 0xca, 0xf7, 0x2a, 0x95, 0x5c, 0xa5, 0x15, 0x68, 0x2a, 0x9c,
	0x22, 0x33, 0x43, 0x46, 0x81, 0x9d, 0xa7, 0xf2, 0x24, 0xf9, 0xf9, 0x59, 0xfe, 0xff, 0xac, 0xeb,
	0x3f, 0x6a, 0x01, 0x15, 0x50, 0xb8, 0xfc, 0xce, 0x38, 0x7b, 0xe9, 0xfb, 0xe2, 0x9e, 0x33, 0x07,
	0x5a, 0x64, 0x0f, 0xd9, 0xe3, 0xa5, 0xe1, 0x32, 0xde, 0x96, 0x4e, 0xae, 0xf5, 0x26, 0xc6, 0xa4,
	0x46, 0x9c, 0x4d, 0xd4, 0x44, 0x35, 0xa4, 0x56, 0xb0, 0x89, 0xda, 0xa8, 0x96, 0xb4, 0x14, 0x8b,
	0x89, 0x96, 0x51, 0xcb, 0x62, 0xc9, 0x99, 0x07, 0x2d, 0xce, 0x93, 0x5e, 0x91, 0x7a, 0x39, 0xb8,
	0x11, 0x75, 0x9a, 0xee, 0x41, 0x53, 0xc7, 0x88, 0xfc, 0xb8, 0x63, 0xd2, 0x1b, 0x3c, 0x98, 0x42,
	0x70, 0xd6, 0x02, 0x8a, 0x8b, 0xd4, 0xc9, 0x65, 0x0b, 0x28, 0xd7, 0x9b, 0x18, 0xbd, 0x3e, 0xbf,
	0x3d, 0x75, 0x3b, 0x7c, 0x3f, 0x78, 0x59, 0x07, 0x50, 0x75, 0xd8, 0x36, 0xe3, 0xd7, 0xa7, 0x4a,
	0xbf, 0xf7, 0x87, 0x96, 0x0e, 0xf5, 0xaa, 0x6b, 0x3e, 0x56, 0x5d, 0xe8, 0x42, 0xda, 0xdb, 0xd6,
	0xa1, 0x53, 0xbf, 0xdb, 0xf2, 0x79, 0x6a, 0xd8, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0xb9,
	0xa6, 0x18, 0xfe, 0x01, 0x00, 0x00,
}
