// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gogo.proto

package google.protobuf;

public final class GoGoProtos {
  private GoGoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(google.protobuf.GoGoProtos.goprotoEnumPrefix);
    registry.add(google.protobuf.GoGoProtos.goprotoEnumStringer);
    registry.add(google.protobuf.GoGoProtos.enumStringer);
    registry.add(google.protobuf.GoGoProtos.enumCustomname);
    registry.add(google.protobuf.GoGoProtos.enumdecl);
    registry.add(google.protobuf.GoGoProtos.enumAlias);
    registry.add(google.protobuf.GoGoProtos.enumEqual);
    registry.add(google.protobuf.GoGoProtos.enumError);
    registry.add(google.protobuf.GoGoProtos.enumvalueCustomname);
    registry.add(google.protobuf.GoGoProtos.enumaliasCustomname);
    registry.add(google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(google.protobuf.GoGoProtos.goprotoSettersAll);
    registry.add(google.protobuf.GoGoProtos.goprotoIsNilAll);
    registry.add(google.protobuf.GoGoProtos.goprotoEnumPrefixAll);
    registry.add(google.protobuf.GoGoProtos.goprotoStringerAll);
    registry.add(google.protobuf.GoGoProtos.verboseEqualAll);
    registry.add(google.protobuf.GoGoProtos.faceAll);
    registry.add(google.protobuf.GoGoProtos.gostringAll);
    registry.add(google.protobuf.GoGoProtos.populateAll);
    registry.add(google.protobuf.GoGoProtos.stringerAll);
    registry.add(google.protobuf.GoGoProtos.onlyoneAll);
    registry.add(google.protobuf.GoGoProtos.equalAll);
    registry.add(google.protobuf.GoGoProtos.descriptionAll);
    registry.add(google.protobuf.GoGoProtos.testgenAll);
    registry.add(google.protobuf.GoGoProtos.benchgenAll);
    registry.add(google.protobuf.GoGoProtos.marshalerAll);
    registry.add(google.protobuf.GoGoProtos.unmarshalerAll);
    registry.add(google.protobuf.GoGoProtos.stableMarshalerAll);
    registry.add(google.protobuf.GoGoProtos.sizerAll);
    registry.add(google.protobuf.GoGoProtos.goprotoEnumStringerAll);
    registry.add(google.protobuf.GoGoProtos.enumStringerAll);
    registry.add(google.protobuf.GoGoProtos.unsafeMarshalerAll);
    registry.add(google.protobuf.GoGoProtos.unsafeUnmarshalerAll);
    registry.add(google.protobuf.GoGoProtos.goprotoExtensionsMapAll);
    registry.add(google.protobuf.GoGoProtos.goprotoUnrecognizedAll);
    registry.add(google.protobuf.GoGoProtos.gogoprotoImport);
    registry.add(google.protobuf.GoGoProtos.protosizerAll);
    registry.add(google.protobuf.GoGoProtos.compareAll);
    registry.add(google.protobuf.GoGoProtos.typedeclAll);
    registry.add(google.protobuf.GoGoProtos.enumdeclAll);
    registry.add(google.protobuf.GoGoProtos.goprotoRegistration);
    registry.add(google.protobuf.GoGoProtos.messagenameAll);
    registry.add(google.protobuf.GoGoProtos.goprotoSizecacheAll);
    registry.add(google.protobuf.GoGoProtos.goprotoUnkeyedAll);
    registry.add(google.protobuf.GoGoProtos.jsonUnAll);
    registry.add(google.protobuf.GoGoProtos.formAll);
    registry.add(google.protobuf.GoGoProtos.compatibleGoOut);
    registry.add(google.protobuf.GoGoProtos.routerPath);
    registry.add(google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(google.protobuf.GoGoProtos.goprotoSetters);
    registry.add(google.protobuf.GoGoProtos.goprotoIsNil);
    registry.add(google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(google.protobuf.GoGoProtos.verboseEqual);
    registry.add(google.protobuf.GoGoProtos.face);
    registry.add(google.protobuf.GoGoProtos.gostring);
    registry.add(google.protobuf.GoGoProtos.populate);
    registry.add(google.protobuf.GoGoProtos.stringer);
    registry.add(google.protobuf.GoGoProtos.onlyone);
    registry.add(google.protobuf.GoGoProtos.equal);
    registry.add(google.protobuf.GoGoProtos.description);
    registry.add(google.protobuf.GoGoProtos.testgen);
    registry.add(google.protobuf.GoGoProtos.benchgen);
    registry.add(google.protobuf.GoGoProtos.marshaler);
    registry.add(google.protobuf.GoGoProtos.unmarshaler);
    registry.add(google.protobuf.GoGoProtos.stableMarshaler);
    registry.add(google.protobuf.GoGoProtos.sizer);
    registry.add(google.protobuf.GoGoProtos.unsafeMarshaler);
    registry.add(google.protobuf.GoGoProtos.unsafeUnmarshaler);
    registry.add(google.protobuf.GoGoProtos.goprotoExtensionsMap);
    registry.add(google.protobuf.GoGoProtos.goprotoUnrecognized);
    registry.add(google.protobuf.GoGoProtos.protosizer);
    registry.add(google.protobuf.GoGoProtos.compare);
    registry.add(google.protobuf.GoGoProtos.typedecl);
    registry.add(google.protobuf.GoGoProtos.messagename);
    registry.add(google.protobuf.GoGoProtos.goprotoSizecache);
    registry.add(google.protobuf.GoGoProtos.goprotoUnkeyed);
    registry.add(google.protobuf.GoGoProtos.keyReflect);
    registry.add(google.protobuf.GoGoProtos.nullable);
    registry.add(google.protobuf.GoGoProtos.embed);
    registry.add(google.protobuf.GoGoProtos.customtype);
    registry.add(google.protobuf.GoGoProtos.customname);
    registry.add(google.protobuf.GoGoProtos.jsontag);
    registry.add(google.protobuf.GoGoProtos.moretags);
    registry.add(google.protobuf.GoGoProtos.casttype);
    registry.add(google.protobuf.GoGoProtos.castkey);
    registry.add(google.protobuf.GoGoProtos.castvalue);
    registry.add(google.protobuf.GoGoProtos.stdtime);
    registry.add(google.protobuf.GoGoProtos.stdduration);
    registry.add(google.protobuf.GoGoProtos.wktpointer);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RouterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gogoproto.Router)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 对应rcp的server name
     * </pre>
     *
     * <code>optional string server = 2;</code>
     * @return Whether the server field is set.
     */
    boolean hasServer();
    /**
     * <pre>
     * 对应rcp的server name
     * </pre>
     *
     * <code>optional string server = 2;</code>
     * @return The server.
     */
    java.lang.String getServer();
    /**
     * <pre>
     * 对应rcp的server name
     * </pre>
     *
     * <code>optional string server = 2;</code>
     * @return The bytes for server.
     */
    com.google.protobuf.ByteString
        getServerBytes();

    /**
     * <pre>
     * http路由地址
     * </pre>
     *
     * <code>optional string router_path = 1;</code>
     * @return Whether the routerPath field is set.
     */
    boolean hasRouterPath();
    /**
     * <pre>
     * http路由地址
     * </pre>
     *
     * <code>optional string router_path = 1;</code>
     * @return The routerPath.
     */
    java.lang.String getRouterPath();
    /**
     * <pre>
     * http路由地址
     * </pre>
     *
     * <code>optional string router_path = 1;</code>
     * @return The bytes for routerPath.
     */
    com.google.protobuf.ByteString
        getRouterPathBytes();

    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @return A list containing the plugins.
     */
    java.util.List<java.lang.String>
        getPluginsList();
    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @return The count of plugins.
     */
    int getPluginsCount();
    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @param index The index of the element to return.
     * @return The plugins at the given index.
     */
    java.lang.String getPlugins(int index);
    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the plugins at the given index.
     */
    com.google.protobuf.ByteString
        getPluginsBytes(int index);
  }
  /**
   * Protobuf type {@code gogoproto.Router}
   */
  public static final class Router extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gogoproto.Router)
      RouterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Router.newBuilder() to construct.
    private Router(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Router() {
      server_ = "";
      routerPath_ = "";
      plugins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Router();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Router(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              routerPath_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              server_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                plugins_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              plugins_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          plugins_ = plugins_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.GoGoProtos.internal_static_gogoproto_Router_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.GoGoProtos.internal_static_gogoproto_Router_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.protobuf.GoGoProtos.Router.class, google.protobuf.GoGoProtos.Router.Builder.class);
    }

    private int bitField0_;
    public static final int SERVER_FIELD_NUMBER = 2;
    private volatile java.lang.Object server_;
    /**
     * <pre>
     * 对应rcp的server name
     * </pre>
     *
     * <code>optional string server = 2;</code>
     * @return Whether the server field is set.
     */
    @java.lang.Override
    public boolean hasServer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 对应rcp的server name
     * </pre>
     *
     * <code>optional string server = 2;</code>
     * @return The server.
     */
    @java.lang.Override
    public java.lang.String getServer() {
      java.lang.Object ref = server_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          server_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 对应rcp的server name
     * </pre>
     *
     * <code>optional string server = 2;</code>
     * @return The bytes for server.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerBytes() {
      java.lang.Object ref = server_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTER_PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object routerPath_;
    /**
     * <pre>
     * http路由地址
     * </pre>
     *
     * <code>optional string router_path = 1;</code>
     * @return Whether the routerPath field is set.
     */
    @java.lang.Override
    public boolean hasRouterPath() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * http路由地址
     * </pre>
     *
     * <code>optional string router_path = 1;</code>
     * @return The routerPath.
     */
    @java.lang.Override
    public java.lang.String getRouterPath() {
      java.lang.Object ref = routerPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          routerPath_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * http路由地址
     * </pre>
     *
     * <code>optional string router_path = 1;</code>
     * @return The bytes for routerPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRouterPathBytes() {
      java.lang.Object ref = routerPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routerPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLUGINS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList plugins_;
    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @return A list containing the plugins.
     */
    public com.google.protobuf.ProtocolStringList
        getPluginsList() {
      return plugins_;
    }
    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @return The count of plugins.
     */
    public int getPluginsCount() {
      return plugins_.size();
    }
    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @param index The index of the element to return.
     * @return The plugins at the given index.
     */
    public java.lang.String getPlugins(int index) {
      return plugins_.get(index);
    }
    /**
     * <pre>
     *插件
     * </pre>
     *
     * <code>repeated string plugins = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the plugins at the given index.
     */
    public com.google.protobuf.ByteString
        getPluginsBytes(int index) {
      return plugins_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, routerPath_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, server_);
      }
      for (int i = 0; i < plugins_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, plugins_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, routerPath_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, server_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < plugins_.size(); i++) {
          dataSize += computeStringSizeNoTag(plugins_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPluginsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.protobuf.GoGoProtos.Router)) {
        return super.equals(obj);
      }
      google.protobuf.GoGoProtos.Router other = (google.protobuf.GoGoProtos.Router) obj;

      if (hasServer() != other.hasServer()) return false;
      if (hasServer()) {
        if (!getServer()
            .equals(other.getServer())) return false;
      }
      if (hasRouterPath() != other.hasRouterPath()) return false;
      if (hasRouterPath()) {
        if (!getRouterPath()
            .equals(other.getRouterPath())) return false;
      }
      if (!getPluginsList()
          .equals(other.getPluginsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServer()) {
        hash = (37 * hash) + SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getServer().hashCode();
      }
      if (hasRouterPath()) {
        hash = (37 * hash) + ROUTER_PATH_FIELD_NUMBER;
        hash = (53 * hash) + getRouterPath().hashCode();
      }
      if (getPluginsCount() > 0) {
        hash = (37 * hash) + PLUGINS_FIELD_NUMBER;
        hash = (53 * hash) + getPluginsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.protobuf.GoGoProtos.Router parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.protobuf.GoGoProtos.Router parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.protobuf.GoGoProtos.Router parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.protobuf.GoGoProtos.Router parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.protobuf.GoGoProtos.Router prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gogoproto.Router}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gogoproto.Router)
        google.protobuf.GoGoProtos.RouterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.GoGoProtos.internal_static_gogoproto_Router_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.GoGoProtos.internal_static_gogoproto_Router_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.protobuf.GoGoProtos.Router.class, google.protobuf.GoGoProtos.Router.Builder.class);
      }

      // Construct using google.protobuf.GoGoProtos.Router.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        server_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        routerPath_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        plugins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.GoGoProtos.internal_static_gogoproto_Router_descriptor;
      }

      @java.lang.Override
      public google.protobuf.GoGoProtos.Router getDefaultInstanceForType() {
        return google.protobuf.GoGoProtos.Router.getDefaultInstance();
      }

      @java.lang.Override
      public google.protobuf.GoGoProtos.Router build() {
        google.protobuf.GoGoProtos.Router result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public google.protobuf.GoGoProtos.Router buildPartial() {
        google.protobuf.GoGoProtos.Router result = new google.protobuf.GoGoProtos.Router(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.server_ = server_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.routerPath_ = routerPath_;
        if (((bitField0_ & 0x00000004) != 0)) {
          plugins_ = plugins_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.plugins_ = plugins_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.GoGoProtos.Router) {
          return mergeFrom((google.protobuf.GoGoProtos.Router)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.protobuf.GoGoProtos.Router other) {
        if (other == google.protobuf.GoGoProtos.Router.getDefaultInstance()) return this;
        if (other.hasServer()) {
          bitField0_ |= 0x00000001;
          server_ = other.server_;
          onChanged();
        }
        if (other.hasRouterPath()) {
          bitField0_ |= 0x00000002;
          routerPath_ = other.routerPath_;
          onChanged();
        }
        if (!other.plugins_.isEmpty()) {
          if (plugins_.isEmpty()) {
            plugins_ = other.plugins_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePluginsIsMutable();
            plugins_.addAll(other.plugins_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.protobuf.GoGoProtos.Router parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.protobuf.GoGoProtos.Router) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object server_ = "";
      /**
       * <pre>
       * 对应rcp的server name
       * </pre>
       *
       * <code>optional string server = 2;</code>
       * @return Whether the server field is set.
       */
      public boolean hasServer() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 对应rcp的server name
       * </pre>
       *
       * <code>optional string server = 2;</code>
       * @return The server.
       */
      public java.lang.String getServer() {
        java.lang.Object ref = server_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            server_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 对应rcp的server name
       * </pre>
       *
       * <code>optional string server = 2;</code>
       * @return The bytes for server.
       */
      public com.google.protobuf.ByteString
          getServerBytes() {
        java.lang.Object ref = server_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          server_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 对应rcp的server name
       * </pre>
       *
       * <code>optional string server = 2;</code>
       * @param value The server to set.
       * @return This builder for chaining.
       */
      public Builder setServer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        server_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应rcp的server name
       * </pre>
       *
       * <code>optional string server = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        server_ = getDefaultInstance().getServer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应rcp的server name
       * </pre>
       *
       * <code>optional string server = 2;</code>
       * @param value The bytes for server to set.
       * @return This builder for chaining.
       */
      public Builder setServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        server_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object routerPath_ = "";
      /**
       * <pre>
       * http路由地址
       * </pre>
       *
       * <code>optional string router_path = 1;</code>
       * @return Whether the routerPath field is set.
       */
      public boolean hasRouterPath() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * http路由地址
       * </pre>
       *
       * <code>optional string router_path = 1;</code>
       * @return The routerPath.
       */
      public java.lang.String getRouterPath() {
        java.lang.Object ref = routerPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            routerPath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * http路由地址
       * </pre>
       *
       * <code>optional string router_path = 1;</code>
       * @return The bytes for routerPath.
       */
      public com.google.protobuf.ByteString
          getRouterPathBytes() {
        java.lang.Object ref = routerPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routerPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * http路由地址
       * </pre>
       *
       * <code>optional string router_path = 1;</code>
       * @param value The routerPath to set.
       * @return This builder for chaining.
       */
      public Builder setRouterPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        routerPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * http路由地址
       * </pre>
       *
       * <code>optional string router_path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRouterPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        routerPath_ = getDefaultInstance().getRouterPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * http路由地址
       * </pre>
       *
       * <code>optional string router_path = 1;</code>
       * @param value The bytes for routerPath to set.
       * @return This builder for chaining.
       */
      public Builder setRouterPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        routerPath_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList plugins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePluginsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          plugins_ = new com.google.protobuf.LazyStringArrayList(plugins_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @return A list containing the plugins.
       */
      public com.google.protobuf.ProtocolStringList
          getPluginsList() {
        return plugins_.getUnmodifiableView();
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @return The count of plugins.
       */
      public int getPluginsCount() {
        return plugins_.size();
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @param index The index of the element to return.
       * @return The plugins at the given index.
       */
      public java.lang.String getPlugins(int index) {
        return plugins_.get(index);
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the plugins at the given index.
       */
      public com.google.protobuf.ByteString
          getPluginsBytes(int index) {
        return plugins_.getByteString(index);
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @param index The index to set the value at.
       * @param value The plugins to set.
       * @return This builder for chaining.
       */
      public Builder setPlugins(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePluginsIsMutable();
        plugins_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @param value The plugins to add.
       * @return This builder for chaining.
       */
      public Builder addPlugins(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePluginsIsMutable();
        plugins_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @param values The plugins to add.
       * @return This builder for chaining.
       */
      public Builder addAllPlugins(
          java.lang.Iterable<java.lang.String> values) {
        ensurePluginsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, plugins_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlugins() {
        plugins_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *插件
       * </pre>
       *
       * <code>repeated string plugins = 3;</code>
       * @param value The bytes of the plugins to add.
       * @return This builder for chaining.
       */
      public Builder addPluginsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePluginsIsMutable();
        plugins_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gogoproto.Router)
    }

    // @@protoc_insertion_point(class_scope:gogoproto.Router)
    private static final google.protobuf.GoGoProtos.Router DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.protobuf.GoGoProtos.Router();
    }

    public static google.protobuf.GoGoProtos.Router getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Router>
        PARSER = new com.google.protobuf.AbstractParser<Router>() {
      @java.lang.Override
      public Router parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Router(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Router> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Router> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public google.protobuf.GoGoProtos.Router getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int GOPROTO_ENUM_PREFIX_FIELD_NUMBER = 62001;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> goprotoEnumPrefix = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_ENUM_STRINGER_FIELD_NUMBER = 62021;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> goprotoEnumStringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUM_STRINGER_FIELD_NUMBER = 62022;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> enumStringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUM_CUSTOMNAME_FIELD_NUMBER = 62023;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.String> enumCustomname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ENUMDECL_FIELD_NUMBER = 62024;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> enumdecl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUM_ALIAS_FIELD_NUMBER = 62025;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> enumAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUM_EQUAL_FIELD_NUMBER = 62026;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> enumEqual = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUM_ERROR_FIELD_NUMBER = 62027;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> enumError = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUMVALUE_CUSTOMNAME_FIELD_NUMBER = 66001;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> enumvalueCustomname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ENUMALIAS_CUSTOMNAME_FIELD_NUMBER = 66002;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> enumaliasCustomname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int GOPROTO_GETTERS_ALL_FIELD_NUMBER = 63001;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoGettersAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_SETTERS_ALL_FIELD_NUMBER = 63010;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoSettersAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_IS_NIL_ALL_FIELD_NUMBER = 63011;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoIsNilAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_ENUM_PREFIX_ALL_FIELD_NUMBER = 63002;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoEnumPrefixAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_STRINGER_ALL_FIELD_NUMBER = 63003;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoStringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int VERBOSE_EQUAL_ALL_FIELD_NUMBER = 63004;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> verboseEqualAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int FACE_ALL_FIELD_NUMBER = 63005;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> faceAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOSTRING_ALL_FIELD_NUMBER = 63006;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> gostringAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int POPULATE_ALL_FIELD_NUMBER = 63007;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> populateAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STRINGER_ALL_FIELD_NUMBER = 63008;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> stringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ONLYONE_ALL_FIELD_NUMBER = 63009;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> onlyoneAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int EQUAL_ALL_FIELD_NUMBER = 63013;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> equalAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int DESCRIPTION_ALL_FIELD_NUMBER = 63014;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> descriptionAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int TESTGEN_ALL_FIELD_NUMBER = 63015;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> testgenAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int BENCHGEN_ALL_FIELD_NUMBER = 63016;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> benchgenAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int MARSHALER_ALL_FIELD_NUMBER = 63017;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> marshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int UNMARSHALER_ALL_FIELD_NUMBER = 63018;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> unmarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STABLE_MARSHALER_ALL_FIELD_NUMBER = 63019;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> stableMarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int SIZER_ALL_FIELD_NUMBER = 63020;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> sizerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_ENUM_STRINGER_ALL_FIELD_NUMBER = 63021;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoEnumStringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUM_STRINGER_ALL_FIELD_NUMBER = 63022;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> enumStringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int UNSAFE_MARSHALER_ALL_FIELD_NUMBER = 63023;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> unsafeMarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int UNSAFE_UNMARSHALER_ALL_FIELD_NUMBER = 63024;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> unsafeUnmarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_EXTENSIONS_MAP_ALL_FIELD_NUMBER = 63025;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoExtensionsMapAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_UNRECOGNIZED_ALL_FIELD_NUMBER = 63026;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoUnrecognizedAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOGOPROTO_IMPORT_FIELD_NUMBER = 63027;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> gogoprotoImport = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int PROTOSIZER_ALL_FIELD_NUMBER = 63028;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> protosizerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int COMPARE_ALL_FIELD_NUMBER = 63029;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> compareAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int TYPEDECL_ALL_FIELD_NUMBER = 63030;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> typedeclAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ENUMDECL_ALL_FIELD_NUMBER = 63031;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> enumdeclAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_REGISTRATION_FIELD_NUMBER = 63032;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoRegistration = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int MESSAGENAME_ALL_FIELD_NUMBER = 63033;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> messagenameAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_SIZECACHE_ALL_FIELD_NUMBER = 63034;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoSizecacheAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_UNKEYED_ALL_FIELD_NUMBER = 63035;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoUnkeyedAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int JSON_UN_ALL_FIELD_NUMBER = 63036;
  /**
   * <pre>
   * json取消后缀的
   * </pre>
   *
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> jsonUnAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int FORM_ALL_FIELD_NUMBER = 63037;
  /**
   * <pre>
   * 所有field都添加form tag，tag值从json
   * </pre>
   *
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> formAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int COMPATIBLE_GO_OUT_FIELD_NUMBER = 63038;
  /**
   * <pre>
   * 兼容go_out，会取消生成某些东西
   * todo gogo里生成go_out多的东西
   * </pre>
   *
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> compatibleGoOut = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ROUTER_PATH_FIELD_NUMBER = 66001;
  /**
   * <pre>
   * 路由地址 serverName path
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      google.protobuf.GoGoProtos.Router> routerPath = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        google.protobuf.GoGoProtos.Router.class,
        google.protobuf.GoGoProtos.Router.getDefaultInstance());
  public static final int GOPROTO_GETTERS_FIELD_NUMBER = 64001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoGetters = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_SETTERS_FIELD_NUMBER = 64010;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoSetters = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_IS_NIL_FIELD_NUMBER = 64011;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoIsNil = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_STRINGER_FIELD_NUMBER = 64003;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoStringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int VERBOSE_EQUAL_FIELD_NUMBER = 64004;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> verboseEqual = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int FACE_FIELD_NUMBER = 64005;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> face = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOSTRING_FIELD_NUMBER = 64006;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> gostring = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int POPULATE_FIELD_NUMBER = 64007;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> populate = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STRINGER_FIELD_NUMBER = 67008;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> stringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ONLYONE_FIELD_NUMBER = 64009;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> onlyone = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int EQUAL_FIELD_NUMBER = 64013;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> equal = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int DESCRIPTION_FIELD_NUMBER = 64014;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> description = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int TESTGEN_FIELD_NUMBER = 64015;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> testgen = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int BENCHGEN_FIELD_NUMBER = 64016;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> benchgen = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int MARSHALER_FIELD_NUMBER = 64017;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> marshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int UNMARSHALER_FIELD_NUMBER = 64018;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> unmarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STABLE_MARSHALER_FIELD_NUMBER = 64019;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> stableMarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int SIZER_FIELD_NUMBER = 64020;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> sizer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int UNSAFE_MARSHALER_FIELD_NUMBER = 64023;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> unsafeMarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int UNSAFE_UNMARSHALER_FIELD_NUMBER = 64024;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> unsafeUnmarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_EXTENSIONS_MAP_FIELD_NUMBER = 64025;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoExtensionsMap = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_UNRECOGNIZED_FIELD_NUMBER = 64026;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoUnrecognized = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int PROTOSIZER_FIELD_NUMBER = 64028;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> protosizer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int COMPARE_FIELD_NUMBER = 64029;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> compare = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int TYPEDECL_FIELD_NUMBER = 64030;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> typedecl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int MESSAGENAME_FIELD_NUMBER = 64033;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> messagename = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_SIZECACHE_FIELD_NUMBER = 64034;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoSizecache = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int GOPROTO_UNKEYED_FIELD_NUMBER = 64035;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoUnkeyed = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int KEY_REFLECT_FIELD_NUMBER = 64036;
  /**
   * <pre>
   * 开启reflect结构体，使用key调用返回interface
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> keyReflect = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NULLABLE_FIELD_NUMBER = 65001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> nullable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int EMBED_FIELD_NUMBER = 65002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> embed = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int CUSTOMTYPE_FIELD_NUMBER = 65003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> customtype = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int CUSTOMNAME_FIELD_NUMBER = 65004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> customname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int JSONTAG_FIELD_NUMBER = 65005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> jsontag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int MORETAGS_FIELD_NUMBER = 65006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> moretags = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int CASTTYPE_FIELD_NUMBER = 65007;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> casttype = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int CASTKEY_FIELD_NUMBER = 65008;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> castkey = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int CASTVALUE_FIELD_NUMBER = 65009;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> castvalue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int STDTIME_FIELD_NUMBER = 65010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> stdtime = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STDDURATION_FIELD_NUMBER = 65011;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> stdduration = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int WKTPOINTER_FIELD_NUMBER = 65012;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> wktpointer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gogoproto_Router_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gogoproto_Router_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngogo.proto\022\tgogoproto\032 google/protobuf" +
      "/descriptor.proto\">\n\006Router\022\016\n\006server\030\002 " +
      "\001(\t\022\023\n\013router_path\030\001 \001(\t\022\017\n\007plugins\030\003 \003(" +
      "\t:;\n\023goproto_enum_prefix\022\034.google.protob" +
      "uf.EnumOptions\030\261\344\003 \001(\010:=\n\025goproto_enum_s" +
      "tringer\022\034.google.protobuf.EnumOptions\030\305\344" +
      "\003 \001(\010:5\n\renum_stringer\022\034.google.protobuf" +
      ".EnumOptions\030\306\344\003 \001(\010:7\n\017enum_customname\022" +
      "\034.google.protobuf.EnumOptions\030\307\344\003 \001(\t:0\n" +
      "\010enumdecl\022\034.google.protobuf.EnumOptions\030" +
      "\310\344\003 \001(\010:2\n\nenum_alias\022\034.google.protobuf." +
      "EnumOptions\030\311\344\003 \001(\010:2\n\nenum_equal\022\034.goog" +
      "le.protobuf.EnumOptions\030\312\344\003 \001(\010:2\n\nenum_" +
      "error\022\034.google.protobuf.EnumOptions\030\313\344\003 " +
      "\001(\010:A\n\024enumvalue_customname\022!.google.pro" +
      "tobuf.EnumValueOptions\030\321\203\004 \001(\t:A\n\024enumal" +
      "ias_customname\022!.google.protobuf.EnumVal" +
      "ueOptions\030\322\203\004 \001(\t:;\n\023goproto_getters_all" +
      "\022\034.google.protobuf.FileOptions\030\231\354\003 \001(\010:;" +
      "\n\023goproto_setters_all\022\034.google.protobuf." +
      "FileOptions\030\242\354\003 \001(\010::\n\022goproto_is_nil_al" +
      "l\022\034.google.protobuf.FileOptions\030\243\354\003 \001(\010:" +
      "?\n\027goproto_enum_prefix_all\022\034.google.prot" +
      "obuf.FileOptions\030\232\354\003 \001(\010:<\n\024goproto_stri" +
      "nger_all\022\034.google.protobuf.FileOptions\030\233" +
      "\354\003 \001(\010:9\n\021verbose_equal_all\022\034.google.pro" +
      "tobuf.FileOptions\030\234\354\003 \001(\010:0\n\010face_all\022\034." +
      "google.protobuf.FileOptions\030\235\354\003 \001(\010:4\n\014g" +
      "ostring_all\022\034.google.protobuf.FileOption" +
      "s\030\236\354\003 \001(\010:4\n\014populate_all\022\034.google.proto" +
      "buf.FileOptions\030\237\354\003 \001(\010:4\n\014stringer_all\022" +
      "\034.google.protobuf.FileOptions\030\240\354\003 \001(\010:3\n" +
      "\013onlyone_all\022\034.google.protobuf.FileOptio" +
      "ns\030\241\354\003 \001(\010:1\n\tequal_all\022\034.google.protobu" +
      "f.FileOptions\030\245\354\003 \001(\010:7\n\017description_all" +
      "\022\034.google.protobuf.FileOptions\030\246\354\003 \001(\010:3" +
      "\n\013testgen_all\022\034.google.protobuf.FileOpti" +
      "ons\030\247\354\003 \001(\010:4\n\014benchgen_all\022\034.google.pro" +
      "tobuf.FileOptions\030\250\354\003 \001(\010:5\n\rmarshaler_a" +
      "ll\022\034.google.protobuf.FileOptions\030\251\354\003 \001(\010" +
      ":7\n\017unmarshaler_all\022\034.google.protobuf.Fi" +
      "leOptions\030\252\354\003 \001(\010:<\n\024stable_marshaler_al" +
      "l\022\034.google.protobuf.FileOptions\030\253\354\003 \001(\010:" +
      "1\n\tsizer_all\022\034.google.protobuf.FileOptio" +
      "ns\030\254\354\003 \001(\010:A\n\031goproto_enum_stringer_all\022" +
      "\034.google.protobuf.FileOptions\030\255\354\003 \001(\010:9\n" +
      "\021enum_stringer_all\022\034.google.protobuf.Fil" +
      "eOptions\030\256\354\003 \001(\010:<\n\024unsafe_marshaler_all" +
      "\022\034.google.protobuf.FileOptions\030\257\354\003 \001(\010:>" +
      "\n\026unsafe_unmarshaler_all\022\034.google.protob" +
      "uf.FileOptions\030\260\354\003 \001(\010:B\n\032goproto_extens" +
      "ions_map_all\022\034.google.protobuf.FileOptio" +
      "ns\030\261\354\003 \001(\010:@\n\030goproto_unrecognized_all\022\034" +
      ".google.protobuf.FileOptions\030\262\354\003 \001(\010:8\n\020" +
      "gogoproto_import\022\034.google.protobuf.FileO" +
      "ptions\030\263\354\003 \001(\010:6\n\016protosizer_all\022\034.googl" +
      "e.protobuf.FileOptions\030\264\354\003 \001(\010:3\n\013compar" +
      "e_all\022\034.google.protobuf.FileOptions\030\265\354\003 " +
      "\001(\010:4\n\014typedecl_all\022\034.google.protobuf.Fi" +
      "leOptions\030\266\354\003 \001(\010:4\n\014enumdecl_all\022\034.goog" +
      "le.protobuf.FileOptions\030\267\354\003 \001(\010:<\n\024gopro" +
      "to_registration\022\034.google.protobuf.FileOp" +
      "tions\030\270\354\003 \001(\010:7\n\017messagename_all\022\034.googl" +
      "e.protobuf.FileOptions\030\271\354\003 \001(\010:=\n\025goprot" +
      "o_sizecache_all\022\034.google.protobuf.FileOp" +
      "tions\030\272\354\003 \001(\010:;\n\023goproto_unkeyed_all\022\034.g" +
      "oogle.protobuf.FileOptions\030\273\354\003 \001(\010:3\n\013js" +
      "on_un_all\022\034.google.protobuf.FileOptions\030" +
      "\274\354\003 \001(\010:0\n\010form_all\022\034.google.protobuf.Fi" +
      "leOptions\030\275\354\003 \001(\010:9\n\021compatible_go_out\022\034" +
      ".google.protobuf.FileOptions\030\276\354\003 \001(\010:H\n\013" +
      "router_path\022\036.google.protobuf.MethodOpti" +
      "ons\030\321\203\004 \001(\0132\021.gogoproto.Router::\n\017goprot" +
      "o_getters\022\037.google.protobuf.MessageOptio" +
      "ns\030\201\364\003 \001(\010::\n\017goproto_setters\022\037.google.p" +
      "rotobuf.MessageOptions\030\212\364\003 \001(\010:9\n\016goprot" +
      "o_is_nil\022\037.google.protobuf.MessageOption" +
      "s\030\213\364\003 \001(\010:;\n\020goproto_stringer\022\037.google.p" +
      "rotobuf.MessageOptions\030\203\364\003 \001(\010:8\n\rverbos" +
      "e_equal\022\037.google.protobuf.MessageOptions" +
      "\030\204\364\003 \001(\010:/\n\004face\022\037.google.protobuf.Messa" +
      "geOptions\030\205\364\003 \001(\010:3\n\010gostring\022\037.google.p" +
      "rotobuf.MessageOptions\030\206\364\003 \001(\010:3\n\010popula" +
      "te\022\037.google.protobuf.MessageOptions\030\207\364\003 " +
      "\001(\010:3\n\010stringer\022\037.google.protobuf.Messag" +
      "eOptions\030\300\213\004 \001(\010:2\n\007onlyone\022\037.google.pro" +
      "tobuf.MessageOptions\030\211\364\003 \001(\010:0\n\005equal\022\037." +
      "google.protobuf.MessageOptions\030\215\364\003 \001(\010:6" +
      "\n\013description\022\037.google.protobuf.MessageO" +
      "ptions\030\216\364\003 \001(\010:2\n\007testgen\022\037.google.proto" +
      "buf.MessageOptions\030\217\364\003 \001(\010:3\n\010benchgen\022\037" +
      ".google.protobuf.MessageOptions\030\220\364\003 \001(\010:" +
      "4\n\tmarshaler\022\037.google.protobuf.MessageOp" +
      "tions\030\221\364\003 \001(\010:6\n\013unmarshaler\022\037.google.pr" +
      "otobuf.MessageOptions\030\222\364\003 \001(\010:;\n\020stable_" +
      "marshaler\022\037.google.protobuf.MessageOptio" +
      "ns\030\223\364\003 \001(\010:0\n\005sizer\022\037.google.protobuf.Me" +
      "ssageOptions\030\224\364\003 \001(\010:;\n\020unsafe_marshaler" +
      "\022\037.google.protobuf.MessageOptions\030\227\364\003 \001(" +
      "\010:=\n\022unsafe_unmarshaler\022\037.google.protobu" +
      "f.MessageOptions\030\230\364\003 \001(\010:A\n\026goproto_exte" +
      "nsions_map\022\037.google.protobuf.MessageOpti" +
      "ons\030\231\364\003 \001(\010:?\n\024goproto_unrecognized\022\037.go" +
      "ogle.protobuf.MessageOptions\030\232\364\003 \001(\010:5\n\n" +
      "protosizer\022\037.google.protobuf.MessageOpti" +
      "ons\030\234\364\003 \001(\010:2\n\007compare\022\037.google.protobuf" +
      ".MessageOptions\030\235\364\003 \001(\010:3\n\010typedecl\022\037.go" +
      "ogle.protobuf.MessageOptions\030\236\364\003 \001(\010:6\n\013" +
      "messagename\022\037.google.protobuf.MessageOpt" +
      "ions\030\241\364\003 \001(\010:<\n\021goproto_sizecache\022\037.goog" +
      "le.protobuf.MessageOptions\030\242\364\003 \001(\010::\n\017go" +
      "proto_unkeyed\022\037.google.protobuf.MessageO" +
      "ptions\030\243\364\003 \001(\010:6\n\013key_reflect\022\037.google.p" +
      "rotobuf.MessageOptions\030\244\364\003 \001(\t:1\n\010nullab" +
      "le\022\035.google.protobuf.FieldOptions\030\351\373\003 \001(" +
      "\010:.\n\005embed\022\035.google.protobuf.FieldOption" +
      "s\030\352\373\003 \001(\010:3\n\ncustomtype\022\035.google.protobu" +
      "f.FieldOptions\030\353\373\003 \001(\t:3\n\ncustomname\022\035.g" +
      "oogle.protobuf.FieldOptions\030\354\373\003 \001(\t:0\n\007j" +
      "sontag\022\035.google.protobuf.FieldOptions\030\355\373" +
      "\003 \001(\t:1\n\010moretags\022\035.google.protobuf.Fiel" +
      "dOptions\030\356\373\003 \001(\t:1\n\010casttype\022\035.google.pr" +
      "otobuf.FieldOptions\030\357\373\003 \001(\t:0\n\007castkey\022\035" +
      ".google.protobuf.FieldOptions\030\360\373\003 \001(\t:2\n" +
      "\tcastvalue\022\035.google.protobuf.FieldOption" +
      "s\030\361\373\003 \001(\t:0\n\007stdtime\022\035.google.protobuf.F" +
      "ieldOptions\030\362\373\003 \001(\010:4\n\013stdduration\022\035.goo" +
      "gle.protobuf.FieldOptions\030\363\373\003 \001(\010:3\n\nwkt" +
      "pointer\022\035.google.protobuf.FieldOptions\030\364" +
      "\373\003 \001(\010BD\n\017google.protobufB\nGoGoProtosZ%g" +
      "ithub.com/coderyw/protobuf/gogoproto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_gogoproto_Router_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gogoproto_Router_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gogoproto_Router_descriptor,
        new java.lang.String[] { "Server", "RouterPath", "Plugins", });
    goprotoEnumPrefix.internalInit(descriptor.getExtensions().get(0));
    goprotoEnumStringer.internalInit(descriptor.getExtensions().get(1));
    enumStringer.internalInit(descriptor.getExtensions().get(2));
    enumCustomname.internalInit(descriptor.getExtensions().get(3));
    enumdecl.internalInit(descriptor.getExtensions().get(4));
    enumAlias.internalInit(descriptor.getExtensions().get(5));
    enumEqual.internalInit(descriptor.getExtensions().get(6));
    enumError.internalInit(descriptor.getExtensions().get(7));
    enumvalueCustomname.internalInit(descriptor.getExtensions().get(8));
    enumaliasCustomname.internalInit(descriptor.getExtensions().get(9));
    goprotoGettersAll.internalInit(descriptor.getExtensions().get(10));
    goprotoSettersAll.internalInit(descriptor.getExtensions().get(11));
    goprotoIsNilAll.internalInit(descriptor.getExtensions().get(12));
    goprotoEnumPrefixAll.internalInit(descriptor.getExtensions().get(13));
    goprotoStringerAll.internalInit(descriptor.getExtensions().get(14));
    verboseEqualAll.internalInit(descriptor.getExtensions().get(15));
    faceAll.internalInit(descriptor.getExtensions().get(16));
    gostringAll.internalInit(descriptor.getExtensions().get(17));
    populateAll.internalInit(descriptor.getExtensions().get(18));
    stringerAll.internalInit(descriptor.getExtensions().get(19));
    onlyoneAll.internalInit(descriptor.getExtensions().get(20));
    equalAll.internalInit(descriptor.getExtensions().get(21));
    descriptionAll.internalInit(descriptor.getExtensions().get(22));
    testgenAll.internalInit(descriptor.getExtensions().get(23));
    benchgenAll.internalInit(descriptor.getExtensions().get(24));
    marshalerAll.internalInit(descriptor.getExtensions().get(25));
    unmarshalerAll.internalInit(descriptor.getExtensions().get(26));
    stableMarshalerAll.internalInit(descriptor.getExtensions().get(27));
    sizerAll.internalInit(descriptor.getExtensions().get(28));
    goprotoEnumStringerAll.internalInit(descriptor.getExtensions().get(29));
    enumStringerAll.internalInit(descriptor.getExtensions().get(30));
    unsafeMarshalerAll.internalInit(descriptor.getExtensions().get(31));
    unsafeUnmarshalerAll.internalInit(descriptor.getExtensions().get(32));
    goprotoExtensionsMapAll.internalInit(descriptor.getExtensions().get(33));
    goprotoUnrecognizedAll.internalInit(descriptor.getExtensions().get(34));
    gogoprotoImport.internalInit(descriptor.getExtensions().get(35));
    protosizerAll.internalInit(descriptor.getExtensions().get(36));
    compareAll.internalInit(descriptor.getExtensions().get(37));
    typedeclAll.internalInit(descriptor.getExtensions().get(38));
    enumdeclAll.internalInit(descriptor.getExtensions().get(39));
    goprotoRegistration.internalInit(descriptor.getExtensions().get(40));
    messagenameAll.internalInit(descriptor.getExtensions().get(41));
    goprotoSizecacheAll.internalInit(descriptor.getExtensions().get(42));
    goprotoUnkeyedAll.internalInit(descriptor.getExtensions().get(43));
    jsonUnAll.internalInit(descriptor.getExtensions().get(44));
    formAll.internalInit(descriptor.getExtensions().get(45));
    compatibleGoOut.internalInit(descriptor.getExtensions().get(46));
    routerPath.internalInit(descriptor.getExtensions().get(47));
    goprotoGetters.internalInit(descriptor.getExtensions().get(48));
    goprotoSetters.internalInit(descriptor.getExtensions().get(49));
    goprotoIsNil.internalInit(descriptor.getExtensions().get(50));
    goprotoStringer.internalInit(descriptor.getExtensions().get(51));
    verboseEqual.internalInit(descriptor.getExtensions().get(52));
    face.internalInit(descriptor.getExtensions().get(53));
    gostring.internalInit(descriptor.getExtensions().get(54));
    populate.internalInit(descriptor.getExtensions().get(55));
    stringer.internalInit(descriptor.getExtensions().get(56));
    onlyone.internalInit(descriptor.getExtensions().get(57));
    equal.internalInit(descriptor.getExtensions().get(58));
    description.internalInit(descriptor.getExtensions().get(59));
    testgen.internalInit(descriptor.getExtensions().get(60));
    benchgen.internalInit(descriptor.getExtensions().get(61));
    marshaler.internalInit(descriptor.getExtensions().get(62));
    unmarshaler.internalInit(descriptor.getExtensions().get(63));
    stableMarshaler.internalInit(descriptor.getExtensions().get(64));
    sizer.internalInit(descriptor.getExtensions().get(65));
    unsafeMarshaler.internalInit(descriptor.getExtensions().get(66));
    unsafeUnmarshaler.internalInit(descriptor.getExtensions().get(67));
    goprotoExtensionsMap.internalInit(descriptor.getExtensions().get(68));
    goprotoUnrecognized.internalInit(descriptor.getExtensions().get(69));
    protosizer.internalInit(descriptor.getExtensions().get(70));
    compare.internalInit(descriptor.getExtensions().get(71));
    typedecl.internalInit(descriptor.getExtensions().get(72));
    messagename.internalInit(descriptor.getExtensions().get(73));
    goprotoSizecache.internalInit(descriptor.getExtensions().get(74));
    goprotoUnkeyed.internalInit(descriptor.getExtensions().get(75));
    keyReflect.internalInit(descriptor.getExtensions().get(76));
    nullable.internalInit(descriptor.getExtensions().get(77));
    embed.internalInit(descriptor.getExtensions().get(78));
    customtype.internalInit(descriptor.getExtensions().get(79));
    customname.internalInit(descriptor.getExtensions().get(80));
    jsontag.internalInit(descriptor.getExtensions().get(81));
    moretags.internalInit(descriptor.getExtensions().get(82));
    casttype.internalInit(descriptor.getExtensions().get(83));
    castkey.internalInit(descriptor.getExtensions().get(84));
    castvalue.internalInit(descriptor.getExtensions().get(85));
    stdtime.internalInit(descriptor.getExtensions().get(86));
    stdduration.internalInit(descriptor.getExtensions().get(87));
    wktpointer.internalInit(descriptor.getExtensions().get(88));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
