// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto3.proto

package proto3_proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "github.com/coderyw/protobuf/proto/test_proto"
	github_com_coderyw_go_proto_validators "github.com/coderyw/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Message) Validate() error {
	if this.Nested != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(this.Nested); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Nested", err)
		}
	}
	// Validation of proto3 map<> fields is unsupported.
	if this.Proto2Field != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(this.Proto2Field); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Proto2Field", err)
		}
	}
	// Validation of proto3 map<> fields is unsupported.
	if this.Anything != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(this.Anything); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Anything", err)
		}
	}
	for _, item := range this.ManyThings {
		if item != nil {
			if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_coderyw_go_proto_validators.FieldError("ManyThings", err)
			}
		}
	}
	if this.Submessage != nil {
		if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(this.Submessage); err != nil {
			return github_com_coderyw_go_proto_validators.FieldError("Submessage", err)
		}
	}
	for _, item := range this.Children {
		if item != nil {
			if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_coderyw_go_proto_validators.FieldError("Children", err)
			}
		}
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *Nested) Validate() error {
	return nil
}
func (this *MessageWithMap) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *IntMap) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *IntMaps) Validate() error {
	for _, item := range this.Maps {
		if item != nil {
			if err := github_com_coderyw_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_coderyw_go_proto_validators.FieldError("Maps", err)
			}
		}
	}
	return nil
}
func (this *TestUTF8) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
