// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto3.proto

package proto3_proto

import (
	fmt "fmt"
	_ "github.com/coderyw/protobuf/proto/test_proto"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
